### ISSUE TITLE
Admin : éviter de se loguer/deloguer pour vérifier infos membres

### ISSUE THREAD

**Issue by alexxxxxxxxxxxxx** [wwoof/webapp#101]
Une fois l’identité d’un membre prise pouvoir voir qu’on est encore en admin et rechanger sans être obligée de se deloguer/reloguer

**Comment by gzurbach** [comment]
Fixé !

**Comment by alexxxxxxxxxxxxx** [comment]
Yo c'est trop bien ! Merci infiniment.
