### ISSUE TITLE
Retrouver le champs interne des commentaires

### ISSUE THREAD

**Issue by alexxxxxxxxxxxxx** [wwoof/webapp#102]
En admin !

**Comment by gzurbach** [comment]
Par exemple : 
 - Voir : https://app.wwoof.fr/host/119
 - Editer : https://app.wwoof.fr/host/119/edit (en bas de la page)

Ce n'est que pour les hôtes à ce jour, je vais créer un autre bug pour les notes des wwoofeurs.

**Comment by alexxxxxxxxxxxxx** [comment]
Merciiiiiiiiiiiii !
