### ISSUE TITLE
Afficher le nbr d'hôte par recherche

### ISSUE THREAD

**Issue by alexxxxxxxxxxxxx** [wwoof/webapp#105]
par critères, par départements...

Je sais tu m'as dit qu'il y avait un bug mais dès qu'il sera fixé, préviens moi. Ce sera super aussi bien pour nos membres que nous ;-)

**Comment by gzurbach** [comment]
Le bug est fixe dans l'outil que j'utilise donc je pense pouvoir le rajouter assez simplement. Mais sachant que la carte indique le nombre d'hôtes je me disais que peut-etre ce n'est plus la peine. Qu'est-ce que tu en penses ?

**Comment by alexxxxxxxxxxxxx** [comment]
Exact, merci beaucoup ! ! ! !
