### ISSUE TITLE
- URGENT - radiation Hôte

### ISSUE THREAD

**Issue by Virg-WF** [wwoof/webapp#111]
Manuel avait radié un hôte qui apparait tjs ds la liste

**Comment by gzurbach** [comment]
Merci de m'envoyer un email avec les infos de l’hôte.

**Comment by Virg-WF** [comment]
Terra contre courant , Xavier, Haute Corse, terracontrecourant@gmail.com

**Comment by gzurbach** [comment]
Fixé.
