### ISSUE TITLE
URGENT - Nouv tarif

### ISSUE THREAD

**Issue by Virg-WF** [wwoof/webapp#113]
le prix des timbres ayant augmentés, il faudrait modifier le montant des cotisations. 
Pour une livraison en France métropolitaine, pour une personne on passe à 38.51
Pour une livraison en France métropolitaine, pour 2 personnes on passe à 43.51
Pour une livraison en Outre Mer, Zone 1, pour une personne on passe  à 38.56
Pour une livraison en Outre Mer, Zone 1, pour 2 personnes on passe à 43.56
Pour une livraison en Outre Mer, Zone 2, pour une personne on passe à 41.56
Pour une livraison en Outre Mer, Zone 2, pour 2 personnes on passe à 46.56
Pour une livraison en Europe, pour une personne on passe à 41.20
Pour une livraison en Europe, pour 2 personnes on passe à 46.20
Pour une livraison en International, pour une personne on passe à 43
Pour une livraison en International, pour 2 personnes on passe à 48

**Comment by Virg-WF** [comment]
Une fois les nouv tarifs mis en place tu peux m'en informer stp, pour qu'Alex puisse faire le changt sur le site. Merci.

**Comment by gzurbach** [comment]
Le site ne fait pas de distinction actuellement entre une et deux personnes pour les tarifs postaux. Je ne vais pas changer cela maintenant. Merci de me donner les nouveaux tarifs postaux **uniques** pour chaque région tels que indiqués sur le site.

**Comment by Virg-WF** [comment]
Ok, voici les nouv tarifs postaux :
France métropolitaine : 3.51
Outre Mer, Zone 1 : 3.56
Outre Mer, Zone 2 : 6.56
Europe : 6.20
International : 8

**Comment by Virg-WF** [comment]
Salut Guillaume, on met le chgt de tarif de côté, pour quelques jours, car le poids des livrest papiers a augmenté et je dois donc calculer le prix de revient des nouveaux timbres.

**Comment by Virg-WF** [comment]
Salut Guillaume, voici donc les nouveaux frais postaux à mettre en ligne stp: France 4,56
Europe 8,00 et international 11,00 euros. Pour Outre Mer 1 : 7,66  et Outre Mer 2 : 11,38

**Comment by gzurbach** [comment]
Fixé.
