### ISSUE TITLE
Connexion impossible pour 'farmstay@lescostils.com'

### ISSUE THREAD

**Issue by alexxxxxxxxxxxxx** [wwoof/webapp#114]
Cet hôte m'a appelé et j'ai essayé avec ses codes et on retombe sur la page d'acceuil de connexion...
Il est sous safari, navigateur anglais

**Comment by gzurbach** [comment]
Pourrais-tu essayer avec un autre navigateur ? Les anciennes versions de Safari ne marchent pas bien.

**Comment by alexxxxxxxxxxxxx** [comment]
je viens d'essayer et c'est OK, je lui dit quoi prb de navigateur ?

**Comment by gzurbach** [comment]
Oui c'est le plus simple, il peut télécharger Chrome ou Firefox gratuitement.
