### ISSUE TITLE
Ferme des Côtes de Fontbonne

### ISSUE THREAD

**Issue by alexxxxxxxxxxxxx** [wwoof/webapp#115]
Cette ferme est en appro (l'hôte nous l'a dit) depuis le 15 et j'ai vérifié c'est vrai.
Par contre, on ne l'a voit pas mais si on tape son nom, si.
AU SECOURS !
Y'en a t-il d'autres ?

**Comment by alexxxxxxxxxxxxx** [comment]
un truc peut-être utile... ? ! 
La liste des appro tient sur deux pages, après il dit qu'il n'y en a plus MAIS dès qu'on en termine une, une autre se rajoute etc...
Est ce que ça ne viendrait pas de là ? Peut-être que tout ne se charge pas.
Je ne sais pas si je suis claire !

**Comment by gzurbach** [comment]
Je vais jeter un coup d'oeil ce weekend.

**Comment by gzurbach** [comment]
Le but principal étant de pouvoir supprimer les fermes non approuvées pour nettoyer tout ça.

**Comment by alexxxxxxxxxxxxx** [comment]
c'est clair merci beaucoup, mais là, ne touche pas à ce compte, je suis en plein mic-mac ;-)

**Comment by samiringo** [comment]
Fixé.
