### ISSUE TITLE
rejet demabde cotisation à payer

### ISSUE THREAD

**Issue by alexxxxxxxxxxxxx** [wwoof/webapp#117]
J'ai rejeté les Tipis de BYDDY mais ça m'a mit HOTE approuvé
En me connetctant avec son mail on me dit que "Votre profil hôte n'a pas pu être approuvé par notre équipe. Ceci probablement parce qu'il ne remplit pas toutes les conditions pour devenir un hôte WWOOF." lorsque je suis sur mon profil MAIS sur la page BIENVENUE on em demande de payer...

**Comment by gzurbach** [comment]
Fixé.

**Comment by alexxxxxxxxxxxxx** [comment]
le problème est à nouveau là... pour LA METTRIE, sebastien bellemene... (ce sont les noms de fermes)

**Comment by alexxxxxxxxxxxxx** [comment]
idem = Elevage de aupas

**Comment by alexxxxxxxxxxxxx** [comment]
BORDES aussi ! J'arrête le srefus.
j'espère qu'ils n'ont pas tous reçu un mail comme quoi ils étaient approuvés...
Peux tu me drie que je corrige au besoin?

**Comment by gzurbach** [comment]
Je n'arrive pas a reproduire. Il faudrait qu'on regarde via Skype.

**Comment by gzurbach** [comment]
Fixé.
