### ISSUE TITLE
Problème de renouvellement d'hôte radié

### ISSUE THREAD

**Issue by alexxxxxxxxxxxxx** [wwoof/webapp#121]
L'hôte "Domaine Le Nepali" qui est un hôte radié a réussi à renouveler ! ! !
Heureusement, je l'ai vu donc je l'ai remboursé via paypal, supprimé son paiement, changé son mail comme ça il ne pourra plus se connecter.
Y a t'il une façon d'éviter ça à l'avenir ? Ou est-ce que je dois par exemple changer tous les mails des radiés comme ça il leur sera impossible de se connecetre et renouveler ?

**Comment by gzurbach** [comment]
Il faut que je m'occupe de ça au plus vite. Il vaut mieux éviter de changer les adresses email des utilisateurs si possible. Je pense que ce qui a du se passer est que nous lui avons envoyé un email de rappel de fin de d’adhésion.
Je m'en occupe au plus vite. Désolé pour le délai.

**Comment by gzurbach** [comment]
Tasks: 
- [ ] Do not allow suspended hosts to log in the app
- [ ] Do not send reminders to suspended hosts
- [ ] Add icon for suspended hosts

**Comment by gzurbach** [comment]
Fixé. Les utilisateurs suspendus (hôte ou wwoofeur) ne recevront plus de rappel de cotisation.

**Comment by alexxxxxxxxxxxxx** [comment]
Génial, merci bcp !
