### ISSUE TITLE
Ajouter un champ pour la date d'envoi du livret papier

### ISSUE THREAD

**Issue by Virg-WF** [wwoof/webapp#122]
Ajout d'un champ permettant d'indiquer la date d'envoi du livret papier.

**Comment by gzurbach** [comment]
On est dessus, ça devrait être assez rapide. On pensait aussi te rajouter un bouton dans le site pour dire "livret envoyé". La date d'envoi du livret papier serait la date à laquelle tu cliques sur ce bouton. Ça te semble bien ?

**Comment by Virg-WF** [comment]
oui ça me semble parfait !

**Comment by Virg-WF** [comment]
Bonjour Guillaume, as tu pu avancer sur ce point ? A bientôt...
