### ISSUE TITLE
Problème de site web hôte et de mises à jour infos du coup...

### ISSUE THREAD

**Issue by alexxxxxxxxxxxxx** [wwoof/webapp#124]
Salut Guillaume,

L’hôte  « La Ramonette » ne parvient pas à enregistrer ses changements car en cliquant sur enregistrer la case site web invalide se met en rouge alors qu’elle n’a, justement, pas de site.

**Comment by gzurbach** [comment]
Je viens de de vérifier. La case "adresse" (adresse postale) n'est pas renseignée. L'utilisateur doit donc renseigner son adresse. Pas de bug donc.

**Comment by alexxxxxxxxxxxxx** [comment]
Non car en trichant (plein d'espaces) ça ne fonctionen pa snon plus ET EN PLUS je recontre un souci pour "manu.poittevin@gmail.com" je mets son texte à jour mais je ne peux pas enregistrer, le message dit que des infos sont manquantes (cf pj)

**Comment by gzurbach** [comment]
Fixé.
