### ISSUE TITLE
La Ferme de Blayac introuvable / Aveyron

### ISSUE THREAD

**Issue by alexxxxxxxxxxxxx** [wwoof/webapp#128]
Si on tape son nom on la trouve mais ça voudrait dire qu'on la connait déjà...

En revanche en tapant Aveyron elle ne ressort pas (13 hôtes) et bien en recherche carte non plus. Elle est pourtant active et elle n'a plus de demande

**Comment by Chinow** [comment]
Aujourd'hui le champ de recherche ne recherche pas dans l'adresse de la ferme, ni dans son département.
 Elle est bien présente si aucun filtre n'est appliqué : 
https://app.wwoof.fr/hosts?lat=43.92645912054985&lon=3.059520721435547&mapZoom=12&searchTerm=

Nous allons essayer d'ajouter les départements comme élément de recherche du champ text, afin d'avoir un comportement plus intuitif.

**Comment by alexxxxxxxxxxxxx** [comment]
Bonjour Maxime,

 

Merci pour le futur ajout du champ département !

En attendant, qu’as-tu entré pour trouver la Ferme de Blayac ?

A plus tard,

 

Alexandra de l'équipe WWOOF France
logoOutlook
 <http://www.wwoof.fr/> www.wwoof.fr

 <http://www.facebook.com/pages/Wwoof-France/172038322894280> http://www.facebook.com/pages/Wwoof-France/172038322894280
Membre de l'association WWOOF International  <http://www.wwoofinternational.org/> www.wwoofinternational.org

P Avant d'imprimer cet e-mail, réfléchissons à l'impact sur l'environnement. 
ECOSIA : le moteur de recherche écologique

 

De : Maxime Viry [mailto:notifications@github.com] 
Envoyé : jeudi 5 mars 2015 23:14
À : wwoof/webapp
Cc : Alexandra Denais
Objet : Re: [webapp] La Ferme de Blayac introuvable / Aveyron (#128)

 

Aujourd'hui le champ de recherche ne recherche pas dans l'adresse de la ferme, ni dans son département.
Elle est bien présente si aucun filtre n'est appliqué : 
https://app.wwoof.fr/hosts?lat=43.92645912054985 <https://app.wwoof.fr/hosts?lat=43.92645912054985&lon=3.059520721435547&mapZoom=12&searchTerm=> &lon=3.059520721435547&mapZoom=12&searchTerm=

Nous allons essayer d'ajouter les départements comme élément de recherche du champ text, afin d'avoir un comportement plus intuitif.

**Comment by Chinow** [comment]
J'ai entré son nom, Il est aussi possible de zoomer directement dessus si tu connais sa position.
Je suis d'accord que ce n'est pas très intuitif si tu ne connais que son département. 

La modification est en cours de validation, on s'assure qu' elle n'a pas d'effet indésirable, et ne elle devrait plus tarder.

**Comment by alexxxxxxxxxxxxx** [comment]
Merci encore Maxime ! Je crois que c’est toi qui t’es amusé à faire la carte, c’est toi qui travaillais chez le grand portail médical de France ou quelque chose du genre non ? C’est chouette que tu aies donné de ton temps pour nous. Le résultat est trop bien, la carte est trop géniale. A son arrivée, on était hystériques et aujourd’hui, on est quotidiennement ravis de l’avoir et nos adhérents aussi ! ! !

 

 

 

Alexandra de l'équipe WWOOF France
logoOutlook
 <http://www.wwoof.fr/> www.wwoof.fr

 <http://www.facebook.com/pages/Wwoof-France/172038322894280> http://www.facebook.com/pages/Wwoof-France/172038322894280
Membre de l'association WWOOF International  <http://www.wwoofinternational.org/> www.wwoofinternational.org

P Avant d'imprimer cet e-mail, réfléchissons à l'impact sur l'environnement. 
ECOSIA : le moteur de recherche écologique

 

De : Maxime Viry [mailto:notifications@github.com] 
Envoyé : vendredi 6 mars 2015 18:12
À : wwoof/webapp
Cc : Alexandra Denais
Objet : Re: [webapp] La Ferme de Blayac introuvable / Aveyron (#128)

 

J'ai entré son nom, Il est aussi possible de zoomer directement dessus si tu connais sa position.
Je suis d'accord que ce n'est pas très intuitif si tu ne connais que son département. 

La modification est en cours de validation, on s'assure qu' elle n'a pas d'effet indésirable, et ne elle devrait plus tarder.

**Comment by Chinow** [comment]
Pas de souci =),
Non, moi j'ai travaillé pour l'IGN a la réalisation de ça => http://www.geoportail.gouv.fr/accueil
et avec la DGEFP pour la réalisation du SI des Missions Locales présente ici => https://www.i-milo.fr/

Aucun problème, c'etait un plaisir de travailler dessus, quand Pedro m'a parle de son projet et du besoin d'avoir une carte, je me suis dit que je pourrai mettre a profit ce que j'ai appris en travaillant avec l'IGN pour une cause que je respecte. Un jour je ferai du Wwoofing aussi :)

**Comment by Chinow** [comment]
Et voila, c'est déployé,

https://app.wwoof.fr/hosts?lat=44.32384807250689&lon=2.3414611816406246&mapZoom=9&searchTerm=Aveyron
