### ISSUE TITLE
Hôte introuvable si + d'1 critère de recherche fourni

### ISSUE THREAD

**Issue by alexxxxxxxxxxxxx** [wwoof/webapp#133]
Je pense qu'il y a une espèce de bug car lorsqu'on entre "vaucluse + élevage" on ne trouve personne...
Alors que si on entre juste "vaucluse" on a plusieurs hôtes donc au moins une qui fait de l'élevage "les Chèvres des Marins"

**Comment by Chinow** [comment]
Elevage est une "activité proposée", la recherche textuelle ne vas pas chercher dans les activités proposées, pour filtrer par activité il faut utiliser le composant correspondant,

**Comment by alexxxxxxxxxxxxx** [comment]
Bonjour Maxime, que veux tu dire par "composant correspondant" ?
Dans ce cas, quelle est l'utilité pour les hôtes de noter "élevage, boulangerie" etc... si les WWOOFeurs ne peuvent pas faire de recherche dessus ? Eclaire-moi.

**Comment by Chinow** [comment]
Il y a un petit composant sous la barre de rechercher permettant de filtrer par activité proposée.

![image](https://cloud.githubusercontent.com/assets/1569362/6756263/dd8d5aa4-cee5-11e4-82d4-e2c5ce99b702.png)

**Comment by gzurbach** [comment]
Pour rechercher sur les activités il faut utiliser le "composant" (= bouton) en-dessous de la zone de recherche textuelle. 

La recherche textuelle ne regarde que dans la description de la ferme, le nom de la ferme, le department et la ville. Les combinaisons du genre "élevage vaucluse" ne sont pas possibles (on est pas Google !).

Meme si l'hote a indique "élevage" dans sa description et qu'il vit dans le vaucluse on ne va pas le trouver en cherchant "élevage vaucluse", cela demanderait beaucoup de travail pour arriver a ce résultat.

**Comment by alexxxxxxxxxxxxx** [comment]
J'ai compris et je comprends tout à fait les "gars" !
