### ISSUE TITLE
Case commentaire interne pour les WWOOFers

### ISSUE THREAD

**Issue by Virg-WF** [wwoof/webapp#135]
On en avez parlé il me semble.... Il me faudrait un champ commentaire, qui ne serait visible que pour les admins, stp.

**Comment by gzurbach** [comment]
Ce bug existe déjà (cf. #134).

Virginie, il y a un champ 'comment' dans la table wwoofers dans Workbench qui semble correspondre a ce que tu demandes. 
Cependant, ce champ semble contenir parfois des commentaires d'admins mais aussi des descriptions provenant des wwoofers eux-mêmes. C'est vraiment étrange. Est-ce que tu veux utiliser ces données pour comme champ de commentaire ou un nouveau champ ?

**Comment by Virg-WF** [comment]
Salut Guillaume, 
En fait ce champ provient de l'ancienne base, les WWOOfers avaient la possibilité de mettre un commentaire lors de leur inscription mais il ne ressortait pas dans leur profil. On s'en est donc servi pour noter nos commentaires internes. Aussi, on peut très bien utiliser celui-ci, mais y'a t il un moyen de le faire ressortir sur le profil W mais uniquement visible pour les admins ?

**Comment by gzurbach** [comment]
Ca marche on va reutiliser celui-la. Il y a environ 9500 wwoofers qui ont des infos saisies dans ce champ, je dirai que 90% proviennent des wwoofers et 10% de nous. Je me suis dit qu'il serait mieux de ne pas perdre cette information.

**Comment by Virg-WF** [comment]
oui t'as raison si ya moyen de les conserver, c'est vraiment cool !

**Comment by gzurbach** [comment]
Avec un peu de retard : c'est fixé ! 
Seuls les admins peuvent voir/modifier ces notes.

**Comment by Virg-WF** [comment]
le trouve bien le champ sur workbench, mais je ne vois rien quand je suis connectée en admin sur le site.
