### ISSUE TITLE
Extraction base WWOOFers

### ISSUE THREAD

**Issue by Virg-WF** [wwoof/webapp#136]
j'ai voulu faire un export de la base pour la compta et lorsque j'ai cliqué sur "alter view" pour modifier les dates, j'ai eu le message d'erreur suivant : Error getting DDL for objet
![2015-04-08_14-23-48](https://cloud.githubusercontent.com/assets/9193103/7062565/d5256a46-de9e-11e4-9038-4db763034673.png)

**Comment by Virg-WF** [comment]
Pour info, les autres exports ne fonctionnent pas non plus.

**Comment by gzurbach** [comment]
Je sais d'ou ca vient je m'em occupe dans la journée.

**Comment by gzurbach** [comment]
Ok c'est bon. Essaye et dis-moi si ca marche :)

**Comment by Virg-WF** [comment]
non, tjs le même message qui s'affiche

**Comment by gzurbach** [comment]
J'avais oublié un detail. Essaye encore ?

**Comment by Virg-WF** [comment]
Cette fois c'est bon ! Merciiii...
