### ISSUE TITLE
Pas de curseur sur carte

### ISSUE THREAD

**Issue by alexxxxxxxxxxxxx** [wwoof/webapp#137]
Salut,
Comme évoqué dans le mail, La Serre du Bois n'apparait pas en recherche carte car il y a 3 hôtes sur ce lieu-dit !
Biz

**Comment by alexxxxxxxxxxxxx** [comment]
un autre cas visiblement :


De : myriam faure [mailto:chambygon@gmail.com] 
Envoyé : vendredi 10 avril 2015 10:31
À : alexandra@wwoof.fr
Objet : Re: WWOOF France

bonjour alexandra
tout va bien jai pu me connecter à mon compte avec le mot de passe(que je note précieusement désormais)!merci. Par contre notre ferme n 'est pas représentée(avec la goutte deau bleu) sur le département. Quand on fait: apercu des fermes puis qu'on selectionne le chiffre 209 sur la carte de France puis le chiffre 56 pour l ardeche; on devrait apparaitre juste à coté du hote Faure Raphae (on est très proche)l. Comme cest le meme nom de famille il ya  peut etre eu oubli...pour nous cest important car on sait que les wwoofers nous choisissent aussi parce quon est sur la route entre privas et aubenas-les vans. voilou cétait mon dernier souci!
bon week end
myriam

**Comment by gzurbach** [comment]
@Chinow Est-ce qu'il y a une solution simple pour ne pas avoir deux marqueurs qui se superposent lorsque deux fermes sont sur la meme commune ?

**Comment by Chinow** [comment]
J'y reflechis depuis hier.
Il doit y avoir un moyen simple et pratique mais j'ai pas encore trouvé.
Je brainstorm avec moi meme et je vous tiens au courrant.

(Je suis en cours d'installation a Singapore, donc ca sera pas forcement super rapidement corrigé)

**Comment by gzurbach** [comment]
J'ai trouvé ca : https://github.com/jawj/OverlappingMarkerSpiderfier-Leaflet
Qu'est ce que tu en penses ?

Sinon tinket pas Max prends ton temps. Je pense que pour le moment je vais simplement le bouger de 500m pour qu'ils soient tous les deux visibles.

**Comment by gzurbach** [comment]
@alexxxxxxxxxxxxx J'ai fixé manuellement les coordonnées pour ces deux cas en leur donnant des adresses plus précises que simplement la commune. Tu pourras les tenir au courant ?

Voir les fermes :
 - Cas 1 : https://app.wwoof.fr/hosts?lat=43.25395510397325&lon=0.8102416992187499&mapZoom=12
 - Cas 2 : https://app.wwoof.fr/hosts?lat=44.698921513917945&lon=4.39727783203125&mapZoom=12&searchTerm=faure

**Comment by alexxxxxxxxxxxxx** [comment]
Ok je vais leur dire merci beaucoup les gars :-) !

Dans le même genre il y a une hôte bien active mais qui n'a pas de curseur du tout... Il s'agit de "Ferme de la Grande Bastide" est-ce que j'ouvre un autre bug ?

**Comment by gzurbach** [comment]
Je n'ai pas trouvé de "Ferme de la Grande Bastide", est-ce que tu aurais l'adresse email de l’hôte ? J'ai trouvé une "Ferme de la Bastide" (https://app.wwoof.fr/host/1090) mais ils ont un point sur la carte.

**Comment by alexxxxxxxxxxxxx** [comment]
le mail est : fsinoir@yahoo.fr
ET voici une capture qui t'aidera peut-être, merci.

**Comment by alexxxxxxxxxxxxx** [comment]
![grandebastide](https://cloud.githubusercontent.com/assets/9049131/7452037/67b7cd6e-f258-11e4-9e16-907846cebbbd.jpg)

**Comment by gzurbach** [comment]
Est-ce que tu as vu que cette ferme a le statut "invisible" activé ? C'est normal ?

**Comment by gzurbach** [comment]
Si c'est pas normal il faut cliquer sur le bouton "rendre visible" en haut à droite.
https://app.wwoof.fr/host/1236/edit

**Comment by gzurbach** [comment]
Je viens de faire une recherche dans la base de données. On avait 704 hôtes qui partageaient les mêmes coordonnées GPS qu'un autre hôte (donc environ 350 hôtes "invisibles"). 
Je viens de faire tourner un programme pour améliorer la situation et on est descendu à 191 hôtes. La plupart des hôtes restants ne sont plus des membres actifs donc ce n'est pas un problème. La raison pour laquelle ils partagent des coordonnées GPS avec d'autres hôtes et que l'on ne dispose que de la ville et pas de l'adresse exacte (ou bien l'adresse exacte est introuvable par Google, ce qui est commun pour des fermes).
Je reviendrai sur ce problème ultérieurement mais on devrait déjà avoir plus la paix sur ce sujet. Les nouveaux hôtes ne devraient plus avoir ce problème non plus.
