### ISSUE TITLE
Pedagogie

### ISSUE THREAD

**Issue by gzurbach** [wwoof/webapp#140]
Salut!

Je reçois de temps en temps des emails de gens qui me demandent pourquoi il faut payer pour avoir accès a la liste des hôtes.

Je me disais que ça serait pas mal de faire un peu de pédagogie et expliquer ce que fait l’association directement sur la page de paiement (celle ou l'on sélectionne son adhésion).

Quelque chose du genre:

**Pourquoi faut-il payer une adhésion pour faire du wwoofing?**

*L'association WWOOF France est responsable de lister, approuver et contrôler les hôtes afin de garantir la qualité de l’échange entre wwoofeurs et hôtes.*

Qu'est ce que vous en pensez ? Il me faudrait la même version pour les hôtes. Du genre "nous validons les hôtes afin de maintenir la qualité du réseau WWOOF France...".

Aussi, je me disais qu'il faudrait mettre sur la page de création du profil wwoofeur et hôte une liste des deux-trois points les plus important à connaitre, avec un lien vers un document a télécharger pour en savoir plus.

La plupart des gens ne lisent pas le document complet (je ne l'ai pas fait à l’époque) mais si c'est devant leurs yeux ils auront plus de chances de le lire.

Par exemple, pour les wwoofeurs...

 - Lorsque vous contactez un hôte, indiquez toujours votre nom de famille et pays d'origine ainsi que la durée de séjour souhaitée.
 - La durée hebdomadaire du travail ne doit pas dépasser 25 heures.
 - Pensez à prendre un assurance !

Est-ce que vous pourriez me fournir ces infos afin que je puisse les traduire et les mettre dans le site?

Merci!

**Comment by gzurbach** [comment]
@alexxxxxxxxxxxxx @Virg-WF Vous pensez pouvoir m'aider la-dessus ?

**Comment by alexxxxxxxxxxxxx** [comment]
Salut Guillaume,
Oui très bonne idée, je sais que les membres ne lisent pas tout...
Nous te préparons ça pour le milieu de semaine prochaine ainsi que les changements dans le guide du WWOOFing vus suite au skype, ça ira niveau timing ?
Merci pour tout. alex

**Comment by gzurbach** [comment]
Impec !

**Comment by alexxxxxxxxxxxxx** [comment]
Hello,

 

Alors voici ce que nous proposons suite à ton point140 sur Github.
Tout d’abord en ce qui concerne le faite de régler une cotisation : 

 

Du côté WWOOFeurs : Pourquoi faut-il payer une adhésion pour faire du WWOOFing ?

 

Régler une cotisation à WWOOF France, c’est participer au développement de l’association, au déploiement de moyens dont l’équipe a besoin pour sélectionner, approuver et les contrôle ses hôtes afin de garantir les meilleurs échanges entre WWOOFeurs et hôtes !

 

Du côté Hôtes : Pourquoi faut-il payer une adhésion pour faire du WWOOFing ?

 

Régler une cotisation à WWOOF France, c’est participer au développement de l’association et aider une équipe à maintenir la qualité d’un réseau d’échanges !

 

 

 

Ensuite, tu suggères de faire 2-3 rappels de points essentiels

Du côté WWOOFeurs :

-        Lorsque vous contactez un hôte, écrivez-lui toujours avec le mail utilisé pour vous inscrire à l’association et donnez-lui votre nom de famille

-        La durée hebdomadaire des activités partagées ne doit pas excéder 25 heures (sauf entente préalable)

-        N’oubliez pas de signer « La déclaration » une fois chez votre hôte !

 


Du côté Hôtes :

-        Lorsqu’un WWOOFeur vous contacte, vérifiez systématiquement sa bonne adhésion grace à son email/nom via votre profil en cliquant sur l’onglet « WWOOFEURS »

-        La durée hebdomadaire des activités partagées ne doit pas excéder 25 heures (sauf entente préalable)

-        N’oubliez pas de signer « La déclaration » une fois votre WWOOFeur arrivé !

  

 

 

N’hésite pas si tu as besoin d’autres choses, qui pourraient te faciliter la vie, alléger tes mails !

Tu pourrais lancer une invitation via Outlook à l’équipe pour le Skype du 22 ? MERCIIIIIIIIIIII.


Bisous

Alex

 

 

Alexandra de l'équipe WWOOF France
logoOutlook
 <http://www.wwoof.fr/> www.wwoof.fr

 <http://www.facebook.com/pages/Wwoof-France/172038322894280> http://www.facebook.com/pages/Wwoof-France/172038322894280
Membre de l'association WWOOF International  <http://www.wwoofinternational.org/> www.wwoofinternational.org

P Avant d'imprimer cet e-mail, réfléchissons à l'impact sur l'environnement. 
ECOSIA : le moteur de recherche écologique

**Comment by gzurbach** [comment]
Je viens de refaire la page des adhésions : https://app.wwoof.fr/memberships/new?itemCode=WO1&type=W
J'ai modifié un peu le texte pour le mettre en trois points. C'est purement esthétique, mais dis-moi si cette version convient.

**Comment by alexxxxxxxxxxxxx** [comment]
ça me convient tout à fait et ça tombait très bien puisque j'avis reçu un dossier papier jutement ; j'ai pu suivre pas à pas l'inscription et je trouve ça cohérent et beau ! ! ! !
C'est bien aussi qu'une fois le compte créé on choisisse directement si on veut être hôte ou WWOOFeur ! Peut-être est-ce fait depuis un moment mais je ne l'avais pas vu et ça enlèvait une étape : cool !

**Comment by Virg-WF** [comment]
A moi aussi ça me convient parfaitement, comme noté sur github : c'est
clair, net et précis ! 

Le 28.05.2015 12:01, Alexandra Denais a écrit : 

> ça me convient tout à fait et ça tombait très bien puisque j'avis reçu un dossier papier jutement ; j'ai pu suivre pas à pas l'inscription et je trouve ça cohérent et beau ! ! ! !
> C'est bien aussi qu'une fois le compte créé on choisisse directement si on veut être hôte ou WWOOFeur ! Peut-être est-ce fait depuis un moment mais je ne l'avais pas vu et ça enlèvait une étape : cool ! 
> 
> --
> Reply to this email directly or view it on GitHub [1].

 

Links:
------
[1] https://github.com/wwoof/webapp/issues/140#issuecomment-106256929

**Comment by Virg-WF** [comment]
Le 28.05.2015 12:50, virginie@wwoof.fr a écrit : 

> A moi aussi ça me convient parfaitement, comme noté sur github : c'est clair, net et précis ! 
> 
> Le 28.05.2015 12:01, Alexandra Denais a écrit : 
> 
>> ça me convient tout à fait et ça tombait très bien puisque j'avis reçu un dossier papier jutement ; j'ai pu suivre pas à pas l'inscription et je trouve ça cohérent et beau ! ! ! !
>> C'est bien aussi qu'une fois le compte créé on choisisse directement si on veut être hôte ou WWOOFeur ! Peut-être est-ce fait depuis un moment mais je ne l'avais pas vu et ça enlèvait une étape : cool ! 
>> 
>> --
>> Reply to this email directly or view it on GitHub [1].

 

Links:
------
[1] https://github.com/wwoof/webapp/issues/140#issuecomment-106256929
