### ISSUE TITLE
Rafraichissement obligatoire ! ! !

### ISSUE THREAD

**Issue by alexxxxxxxxxxxxx** [wwoof/webapp#142]
Non pas de limonade ou de bière ;-) mais un prb que nous rencontrons depuis une petite semaine. Une fois connectés, en admin ou en tant que membre il faut systématiquement rafraichir la page pour pouvoir accéder aux infos...

cf mail hôte
"De : WWOOFing at Izaut [mailto:wwoof@izaut-rustica.com] 
Envoyé : jeudi 23 avril 2015 14:27
À : alexandra@wwoof.fr
Objet : Re: WWOOF France

Je vois que la site est toujours en plein developpement et tant mieux - la presentation est bien sûr amelioré.

En rapport avec le BUG, c'est toujours la quand j'arrive tout de suite apres Connexion (pas de visibilité).

Mais maintenant plus de definition:

Si je vais au site wwoof.fr d'abord et fait Connexion tout est correct - status adhesion.

Si je vais par le lien https://app.wwoof.fr/host/1735 la probléme est evident.

Ca continue apres des visites de Mon Compte, Mes Adhesions, et autres, mais j'ai trouvé un autre maniére de sortir - 'Recharger la page'. 

Semble qu'un 2eme appel au base de données (mais apres Connexion) corrige la status. Plutôt amusant ! je travaillait avec les logiciels pendant des années et je sais comme il est ...

Cordialement Lee"

**Comment by gzurbach** [comment]
Fixé.

**Comment by gzurbach** [comment]
Alex, est-ce que tu pourrais confirmer que le bug est bien fixé pour cet hôte ? Le comportement qu'il décrit est un peu différent de ce que tu as eu. Je veux être certain d'avoir fixe les deux problèmes. Merci !

**Comment by alexxxxxxxxxxxxx** [comment]
Mmmmmmmmm... nouvelles de Lee.

"De : WWOOFing at Izaut [mailto:wwoof@izaut-rustica.com] 
Envoyé : mardi 28 avril 2015 09:32
À : alexandra@wwoof.fr
Objet : Re: WWOOF France

Bonjour Alexandra,

NO. Reactions pareil. Heureusement des wwoofers ont confirmé que notre page est vraiment visible. C'est que les messages adhesions qui sont inquietant.

Cordialement, Lee"

**Comment by gzurbach** [comment]
Je viens de parler avec Lee, il utilise Safari 5. Il vient de faire un test avec Safari 6 et tout marche correctement. Je vais ajouter un message sur le site pour indiquer que Safari 5 n'est plus supporté (trop de soucis tout le temps). Voir #145.

**Comment by alexxxxxxxxxxxxx** [comment]
merci bcp !
