### ISSUE TITLE
Curseur placé sur France au lieu de La Réunion

### ISSUE THREAD

**Issue by alexxxxxxxxxxxxx** [wwoof/webapp#144]
Pour "Ferme du Bras Mahot", merci !

**Comment by gzurbach** [comment]
Fixé.

**Comment by alexxxxxxxxxxxxx** [comment]
Un nouveau cas toujours pour La Réunion mais qui est placé sur Genève, merci.

Les Jardins de Shambhala

**Comment by gzurbach** [comment]
Fixé.
