### ISSUE TITLE
Différencier une adh WWOOFer SOLO/DUO pour un hôte

### ISSUE THREAD

**Issue by Virg-WF** [wwoof/webapp#147]
Lorsqu’on se connecte en tant qu'hôte et qu'on souhaite vérifier l'adh des WWOOFers, on ne trouve aucune info concernant le second WWOOFer. Aussi, y'a t-il possibilité d'ajouter des informations lorques c'est une adh en duo du type : nom et prénom du second WWOOFer, car il me semble que pour le moment, l'hôte ne peut pas faire de distinguo entre une adh SOLO et DUO.

**Comment by gzurbach** [comment]
Tout à fait raison, c'est un oubli facile à corriger. Je m'en occupe ce weekend !

**Comment by Virg-WF** [comment]
Ok, merci Guillaume !

**Comment by gzurbach** [comment]
Fixé :)
