### ISSUE TITLE
Cases à cocher activités hôtes

### ISSUE THREAD

**Issue by alexxxxxxxxxxxxx** [wwoof/webapp#150]
Pour "Les Ombelles" je n'ai rien pu cocher depuis son profil car en enregistrant j'avais un message d’erreur (celui en rouge).
Je suis donc passée par Workbench pour contourner le problème.
J'ai tenté sur mon compte perso et j'ai pu cocher et enregistrer ensuite. Je ne sais donc pas où se situe le problème

**Comment by alexxxxxxxxxxxxx** [comment]
et mail de cette femme renvoyé par mail pour toi Guillaume

**Comment by gzurbach** [comment]
Fixé. J'ai vu le mail je répondrai ce soir.
