### ISSUE TITLE
Mail pour nouveau mot de passe qui n'arrive jamais...

### ISSUE THREAD

**Issue by alexxxxxxxxxxxxx** [wwoof/webapp#151]
Rien eu après 20 mn d'attente  et j'ai bien regardé dans les SPAMS.

**Comment by gzurbach** [comment]
Ce bug la était coriace et bien caché.

Il est possible que l'envoi d'email n'ait plus fonctionné depuis le 5 avril. Ce qui veut dire qu'on a potentiellement pas envoyé d'emails ces 5 dernières semaines. Ça me semble gros mais possible. Désolé pour ce bug c'est de ma faute :(

**Comment by alexxxxxxxxxxxxx** [comment]
je ne crois pas non , on aurait eu des retours... ;-)
