### ISSUE TITLE
Hôtes sans demande de WWOOFers et pourtants bien actifs...

### ISSUE THREAD

**Issue by alexxxxxxxxxxxxx** [wwoof/webapp#152]
De plus en plus d'hôtes n'ont pas de demandes alors qu'auparavant à cette époque ils étaient full ou d'autres ne se trouvent pas...
Aurais-tu une explication ?

Encore un exemple avec :

"
De : Stéphanie VIVIER [mailto:vivier-stephanie@orange.fr] 
Envoyé : mercredi 20 mai 2015 09:29
À : alexandra@wwoof.fr
Objet : inscription sur le site.

Bonjour.
Depuis 2014,nous sommes inscrits sur le site de wwoofing et depuis quelques temps nous ne recevons plus de mails de propositions et lorsque nous allons sur le site,nous ne trouvons pas notre ferme...Pourriez-vous voir cela?
N° adhérent: H1736.
Merci.
Stéphanie.
"

**Comment by gzurbach** [comment]
Je garde ça pour demain sur Skype.
