### ISSUE TITLE
Probl communication entre workbench et site

### ISSUE THREAD

**Issue by Virg-WF** [wwoof/webapp#153]
J'a effectué quelques modifications sur des profils de W, mais elles ne semblent pas être prise en compte par le site.

**Comment by gzurbach** [comment]
Pas assez d'information pour aider. Il y a plusieurs raisons qui peuvent expliquer cela. Par exemple si le wwoofeur a fait des modifications sur son profil en même temps que toi il a pu écraser tes changements. Dans la mesure du possible il ne faut pas utiliser workbench, toujours privilégier le site.

**Comment by gzurbach** [comment]
Aussi, sait-on jamais, as-tu pensé à cliquer sur "apply" en bas à droite après avoir effectué les modifications ?

**Comment by Virg-WF** [comment]
oui, j'ai bien pensé à cliquer sur "apply". Voici un ex : je suis allée sur workbench pour supp le W2, puisque cette WWOOFeuse à renouveler en SOLO. Je fais donc le nécessaire sur le compte de : fgodet@laposte.net et lorsque je retourne sur le site pour voir si ça a bien été pris en compte et là, le W2 apparait tjs.

**Comment by Virg-WF** [comment]
En fait , je pense que les chgts ne sont pas immédiat, car je viens d'aller voir les comptes qui me posaient probl hier et maintenant c'est ok.

**Comment by gzurbach** [comment]
A mon avis il fallait rafraichir la page (F5). Les changements sont immédiats. Content que ça marche !
