### ISSUE TITLE
Ajouter les frais postaux.

### ISSUE THREAD

**Issue by Virg-WF** [wwoof/webapp#154]
Sur la page de paiement, dans le menu déroulant permettant de choisir son type d'adhésion tu pourrais ajouter pour les adhésion avec livret papier (hors frais de port), stp ?

**Comment by gzurbach** [comment]
Salut Virginie. Je ne comprends pas la question désolé. Il manque un mot dans la phrase non ?

**Comment by Virg-WF** [comment]
ouais t'as raison, pas terrible la construction de ma phrase ! En fait, j'aimerais que tu ajoutes sur la page de paiement une mention indiquant que le prix affiché (35 pour LP pour une personne et 40 pour deux) n'inclus pas les frais de port.

**Comment by gzurbach** [comment]
Ok pas de soucis je m'en occupe des que possible !

**Comment by gzurbach** [comment]
Fixé.

**Comment by Virg-WF** [comment]
C'est clair, net et précis... merci !
