### ISSUE TITLE
Solution médiocre et temporaire pour une hôte cachée derrière une autre (curseur)

### ISSUE THREAD

**Issue by alexxxxxxxxxxxxx** [wwoof/webapp#156]
J'ai masqué temporairement "La Ferme de La Pedra" pour laisser place à "Le Mir" ce matin et elle reçoit à nouveau des demandes. Elles se trouvent dans la même ville, Le Mir est au Lieu-Dit Lô Miro. J'ai les coordonénes GPS grace au site dont tu nous a parlé Guillaume même je ne vois plus où les mettre... En attendant, ça solutionne le problème mais j'espère que La Ferme De La Pedra ne devienne pas furax d'ici peu  :-)

**Comment by Chinow** [comment]
Bonjour !
(Désolé Pedro, je te vol cette réponse :p)

Alors de ce que j'ai vu vous pouvez en tant qu'admin éditer un hôte et tout en bas vous devriez voir les coordonnées GPS de cet hôte, je pense que c'est ici que il faut les changer:
=> https://app.wwoof.fr/host/609/edit

![image](https://cloud.githubusercontent.com/assets/1569362/7863754/a710792a-0590-11e5-861f-921e79f03151.png)

**Comment by alexxxxxxxxxxxxx** [comment]
Merci Maxime, je me connectais en tant qu'admin mais ensuite je changeais d'utilsateur pour être sur le profil de l'hôte... mais nul besoin, merci encore !

**Comment by alexxxxxxxxxxxxx** [comment]
et ça marche ! ! ! !! HI hi hi super, merci les gars

**Comment by gzurbach** [comment]
Merci @Chinow tu assures !

**Comment by Chinow** [comment]
Pas de souci  :)
