### ISSUE TITLE
coordonnées GPS

### ISSUE THREAD

**Issue by Virg-WF** [wwoof/webapp#158]
Salut Guillaume, je n'arrive pas à modifier les coordonnées gps d'un hôte sur l'île de la Réunion pourtant, lorsque j'enregistre les nouvelles valeurs, elles sont prises en compte mais dès que je rafraichis la page se sont de nouveau les anciennes coordonnées qui s'affichent.
Pour info, il s'agit de la ferme : Les jardins de la forêt, Chemin Madrier, 97412 Sainte-Suzanne, La Réunion. Coordonnées trouvées : -20.9699241 et 55.59019680000006

**Comment by gzurbach** [comment]
Il semblerait que tu aies trouvé la solution ? Pour info, tu utilises quel navigateur (et quelle version) ?

Si tu n'es pas sûre : https://whatbrowser.org/

**Comment by gzurbach** [comment]
Sans plus d'infos, je pense que je peux fermer ce bug.

**Comment by Virg-WF** [comment]
Internet explorer 11. La ferme est désormais bien placée.
