### ISSUE TITLE
Bouton WWOOF France ne renvoie pas à la page d'accueil

### ISSUE THREAD

**Issue by VeroWWoof** [wwoof/webapp#159]
Hello
Depuis la page d'approbation des hôtes, le "bouton" WWOOF France en haut à gauche est inactif. Est il possible de le rendre actif pour qu'il nous renvoie vers la page d'accueil du site ?
Merci :)
V.
![capture d ecran 2015-06-04 a 10 03 56](https://cloud.githubusercontent.com/assets/12623351/7979620/1d7396e6-0aa1-11e5-9149-39fd2752bcb7.png)

**Comment by gzurbach** [comment]
C'est normal ! Le bouton n'est pas inactif il est simplement supposé retourner sur la liste des hôtes. Comme tu te trouvais déjà sur cette page, cliquer ce bouton n'a eu aucun effet.
Je pense que ce comportement est attendu mais on peut en discuter vendredi lors de notre Skype.
