### ISSUE TITLE
Page "Aperçu des fermes" ne fonctionne pas

### ISSUE THREAD

**Issue by VeroWWoof** [wwoof/webapp#160]
Hello :)
On nous a signalé un bug : en cliquant sur le bouton "aperçu des fermes" depuis la page "Devenir un W" : rien n'apparaît si ce n'est une page blanche (je viens de le vérifier sur Safari et Firefox).
Merci
V.

**Comment by gzurbach** [comment]
Depuis cette page : http://wwoof.fr/wwoofer2.htm ?

Ça marche pourtant pour moi.

**Comment by VeroWWoof** [comment]
Cela refonctionne :)
:+1:

**Comment by alexxxxxxxxxxxxx** [comment]
Salut, depuis 2 heures environ le site est inaccsessible de nouveau... ;-(
