### ISSUE TITLE
Les tirets dans les départements sont problématiques

### ISSUE THREAD

**Issue by alexxxxxxxxxxxxx** [wwoof/webapp#161]
Cela empêche de trouver TOUS les hôtes du département.

exemple :

Effectivement Philippe, il faut que vous tapiez Hautes-Pyrénées, avec le tiret, c’est vrai que c’est embêtant, alors pour corriger ça j’ai légèrement modifié voter texte qui commence donc par « Situés dans les Hautes Pyrénées, nous accueillons des personnes désirant s'investir dans la création d'une serre (ancienne bergerie avec toiture transparente). (…) ».
Là vous pouvez vérifier, on vous voit mais je vais voir avec Guillaume, notre webmaster, si on peut remédier à ça !
Bonne soirée.
Alexandra de l'équipe WWOOF France
 
----------

Bonjour
quand je tape 65 ou Hautes Pyrénées
dans la recherche d'hôtes nous n’apparaissons pas pourquoi ?

cordialement

Audrey et Philippe

**Comment by gzurbach** [comment]
Je comprends bien le problème. La solution existe mais c'est compliqué (et probablement payant). J'en discuterai avec @Chinow et on te dira quels sont les coûts potentiels.

**Comment by alexxxxxxxxxxxxx** [comment]
;-° Petit oubli de vendredi, as-tu pu contacté @Chinow pour ça ?
Bises

**Comment by Chinow** [comment]
Nous en avons discute plusieurs fois mais les solution sont peu nombreuses et toutes très coûteuses en terme infrastructure nécessaire a leur mise en oeuvre. (Mise en place de services pour deviner la saisie de l'utilisateur a l'image d'un google Map).

Je vais y re-réfléchir bientôt pour voir si je peux cette fois ci trouver un solution simple qui fonctionnerai correctement sans causer des cas étranges.
