### ISSUE TITLE
Navigateur en FR mais mails reçus en EN...

### ISSUE THREAD

**Issue by alexxxxxxxxxxxxx** [wwoof/webapp#162]
voir ci-dessous :

réponse : Mon navigateur est bien en français.

Le 8 juin 2015 15:45, Alexandra <alexandra@wwoof.fr> a écrit :
Bonjour,
 
A mon avis votre navigateur est configuré en anglais car je crois que le site adapte son langage à vos paramètres.
Pouvez-vous me le confirmer ? Ou pas, et dans ce cas j’en parlerai à notre webmaster, Guillaume.
A plus tard,
Alexandra de l'équipe WWOOF France

 

De : Patrick QUERE [mailto:patycoat@gmail.com] 
Objet : Re: [infosweb4] WWOOF France : informations importantes sur le site web ;-)
 
Est-ce possible d'avoir mon compte WOOF en français?

**Comment by gzurbach** [comment]
Le navigateur peut être en Français mais configuré pour voir les sites en anglais.
C'est lié au bug #51. Il faut permettre aux utilisateurs de configurer leur langue.

**Comment by gzurbach** [comment]
Fixé !
