### ISSUE TITLE
Indiquer la capacité d'accueil des hôtes

### ISSUE THREAD

**Issue by gzurbach** [wwoof/webapp#164]
J'ai oublié de vous en parler lors de notre Skype mais je pense rajouter un champ "capacité d'accueil" dans le profil des hôtes.
De cette manière, les wwoofeurs pourront éviter de contacter des hôtes qui ne peuvent pas accueillir leur groupe.
J'ai aussi vu pas mal de messages de wwoofeurs qui cherchent à venir en famille, je pense qu'il faudrait aussi indiquer cela.

Voici la proposition :
 - Les hôtes peuvent indiquer leur capacité d'accueil : 1, 2, 3, 4 ou 5+
 - Les hôtes peuvent aussi cocher une case optionnelle : "Familles OK" (ou "Enfants OK")
 - Les wwoofeurs peuvent préciser lors de leur recherche la capacité voulue et s'ils viennent en famille

Cela pose le problème du travail des moins de 18 ans. J'ai vu dans certains messages des parents demander aux hôtes si les taches proposées s'adaptent aussi à leurs enfants. Ca ressemble plus à des vacances à la ferme qu'a du wwoofing à ce stade. Par conséquent, est-ce un problème d'ajouter cette option "enfants OK" ou non ?

Il y aussi le problème du travail non-rémunéré... si les hôtes indiquent capacité 5+ ca veut tout de même dire que leur ferme tourne grâce aux wwoofeurs. Risque légal pour nous/eux ?

**Comment by alexxxxxxxxxxxxx** [comment]
Très bonnes suggestions !
> pour les enfants ça semble bien mais il faudrait dans ce moment là rajouter une phrase du type astérisque "attention les enfants ne peuvent en aucun cas participer aux activités (+ de 18 ans)". Les hôtes ayant des enfants acceuillent généralement les familles, ils jouent alors entre eux ; c'est bien pour tout le monde. 

> la capacité d'aceuil c'est OK aussi et même très bien. 1/2/3/plus (pas 4 ni 5). Là encore pas de problème car on a des communautés, ou plusieurs amis qui partent aussi ensemble... ce qui ne veut pas dire que toute l'année à tel endroit il y a 10 WWOOFers (et si c'est le cas et qu'ils se font pincer = tant pis = bien fait).

Donc OK tout ça dans les recherches.

:-D

**Comment by Virg-WF** [comment]
j'allais dire comme Alex à savoir, si les enfants peuvent vous accompagner leurs parents, ils ne pourront, en revanche, pas prendre part aux activités. Ok aussi pour ajouter la capacité d'accueil, ça permet aux WWOOFers de mieux cibler leur recherche.

**Comment by gzurbach** [comment]
On y est presque !

<img width="718" alt="screen shot 2015-12-03 at 2 57 13 pm" src="https://cloud.githubusercontent.com/assets/795927/11576812/4180c8d0-99ce-11e5-86a8-ac027cb8d482.png">

**Comment by gzurbach** [comment]
Je vais mettre la valeur par défaut sur "2 wwoofeurs" et ne pas cocher "children" et "pets".

Voilà à quoi ça ressemble à l'affichage: 
<img width="289" alt="screen shot 2015-12-03 at 3 56 04 pm" src="https://cloud.githubusercontent.com/assets/795927/11577980/6b2102f6-99d6-11e5-9280-c1990ba3beee.png">

**Comment by Virg-WF** [comment]
c'est vraiment super ce que tu as ajouté, je pense que les WWOOFers vont vraiment être ravis -;)
