### ISSUE TITLE
Ajouts mentions spécials au moment de remplir la candidature Hôte

### ISSUE THREAD

**Issue by alexxxxxxxxxxxxx** [wwoof/webapp#168]
Suite à mon mail :

"Je remarque que nous demandons pas mal de compléments d’infos aux candidats hôtes car il n’est pas forcément évident de voir s’ils sont en bio. Je sais que c’est bien noté sur la première page, lorsque tu créer ton compte. Mais ensuite, lorsque tu choisis de devenir un hôte, on a cette page ci-dessous que tu connais ;-) et on en parle plus vraiment…

Crois tu possible de glisser après « informations générales » 

« ATTENTION : toute candidature ne mentionnant pas clairement être en bio ou tout du moins utiliser des pratiques saines et respectueuses de l’environnement se verra être refusée ». ?

Et comme tu le suggèrerais, à droite un petit pavé du genre rappel :

Un VVWOOFeur :
-ne peut pas avoir – de 18 ans 
-ne remplace pas un ouvrier
-participe environ une demi-journée à vos activités
-s’implique dans les tâches quotidiennes

Si c’est possible et qu’en plus tu peux le faire rapidement ce serait génial !  Dis-moi."

**Comment by alexxxxxxxxxxxxx** [comment]
je te relance sur cela.
Pense-tu possible de mettre au moment où l'H soumet sa candidature un petit pavé sur fond vert par exemple rappelant :
"Rappel : en demandant à devenir hôte WWOOF vous certifiez être en bio ou tout du moins à utiliser des pratiques saines et respectueuses de l’environnement"


Merci

**Comment by gzurbach** [comment]
Je m'en occupe cette semaine.

**Comment by alexxxxxxxxxxxxx** [comment]
;-) merci

**Comment by gzurbach** [comment]
Voilà c'est fait, tu pourras vérifier Alex?

https://app.wwoof.fr/hosts/new (connecte-toi sur un compte qui n'a pas de profil hôte)

**Comment by alexxxxxxxxxxxxx** [comment]
Merci j'ai vu, alors effectivement c’est bien noté peut être pas suffisamment visible (le faire apparaître en rouge ou bold ?) mais la mention est là donc si tu ne peux pas faire "mieux" tu peux clôturer ce bug.
