### ISSUE TITLE
Hôtes en attente d'appro mais qui ont déjà payé

### ISSUE THREAD

**Issue by alexxxxxxxxxxxxx** [wwoof/webapp#169]
Nosu avons 4 hôtes en attente d'approbation mais donc la cotisation a été réglé.

J'en ai eu deux rejeté avec la cotisation réglée. J'ai fait un remboursement, j'ai réglé ça mais as-tu uen explication ?

https://app.wwoof.fr/hosts?approvalStatus=pending&lat=45.644768217751924&lon=2.30712890625&mapZoom=6

Et toutes ont bien payé sur Paypal sauf yannickborel13@gmail.com "mas de la grotte"

**Comment by alexxxxxxxxxxxxx** [comment]
Salut,

Il y en a d'autres de temps en temps... ^^

**Comment by gzurbach** [comment]
On devrait etre bon maintenant, je viens de fixer le bug aujourd'hui :)

**Comment by alexxxxxxxxxxxxx** [comment]
Génial, merci d'avoir fait vite ;-)
