### ISSUE TITLE
2 paiements pour 1 adhésion

### ISSUE THREAD

**Issue by VeroWWoof** [wwoof/webapp#175]
Hello :)
Je pense qu'il y a un petit bug concernant le WWOOFer "alexandra.lefustec76@live.com" (adhésion duo).
Ils ont eu la possibilité de régler 2 fois leur paiement (un à 21:23:38 et l'autre 21:14:47 le 15 JUIN 2015 = Virginie a vérifié sur Paypal) ce qui a eu pour effet de cumuler les dates sur le site = c'est comme s'ils avaient souscrit pour 2 ans (voir PJ). 
Merci  !!
V. 
<img width="794" alt="capture d ecran 2015-07-21 a 14 48 09" src="https://cloud.githubusercontent.com/assets/12623351/8801081/39a1231a-2fb8-11e5-8f71-9df365742956.png">

**Comment by gzurbach** [comment]
Cette personne m'a contacté par email parce qu'elle avait des difficultés à utiliser le site. J'ai bien vu qu'elle avait deux adhesions mais cela n'avait pas l'air de la déranger. A voir donc avec elle si elle veut un remboursement pour la deuxième année.
Du point de vue du site il n'y a pas vraiment eu de bug. Le membre a simplement payé pour deux ans. Le mieux serait peut-être de rajouter un message d'avertissement?

**Comment by VeroWWoof** [comment]
On peut le clôturer alors : on va rembourser la 2nde année à la demande de la W. Merci !
