### ISSUE TITLE
Envoi rappel renouv

### ISSUE THREAD

**Issue by Virg-WF** [wwoof/webapp#177]
Merci pour cette évolution Guillaume... Toutefois, je voulais vérifier avec toi que le fonctionnement était correct, car sur une page qui contient 20 rappels, j'encoche pour tous les sélectionner mais quand je clique sur "envoyer rappel" les 20 ne partent pas d'un coup. Il y'en a 10, puis 5, puis 3... jusqu'à ce que les 20 partent. Je gagne du tps c'est sûr mais je me demandais si c'était normal que l'envoi ne se fasse pas en un seul coup ?

**Comment by gzurbach** [comment]
Non c'est pas normal. Je vais investiguer ce problème au plus vite. Est-ce que tu pourrais ne pas envoyer de rappels pendant un jour ou deux? Merci !

**Comment by Virg-WF** [comment]
ok ça marche, tu me donneras le feu vert...

**Comment by gzurbach** [comment]
J'ai trouvé la cause du bug. Il va me falloir 2-3 jours avant que je puisse me pencher dessus. En attendant tu peux envoyer des rappels si besoin, je voulais juste verifier qu'on envoie pas de doublons mais c'est bon c'est pas le cas :)

**Comment by gzurbach** [comment]
Fixé!

**Comment by Virg-WF** [comment]
Super, merci...
