### ISSUE TITLE
Disparition du pavé "Documents Utiles" sur le profil W

### ISSUE THREAD

**Issue by VeroWWoof** [wwoof/webapp#178]
Hello Guillaume
Pour info, le pavé documents utiles sur le profil W a disparu. Cela nous a été remonté par roks8@hotmail.com qui cherchait à télécharger la déclaration. Merci !
Bises
V.
<img width="1203" alt="capture d ecran 2015-08-17 a 14 36 42" src="https://cloud.githubusercontent.com/assets/12623351/9304942/65dc1832-44ed-11e5-9e64-0e8ae6ebe7dd.png">

**Comment by gzurbach** [comment]
Mmm tu peux me dire quel navigateur c'est ? Je viens de tester avec Chrome et Firefox et ça semble marcher. Est-ce que je dois accuser Internet Explorer par hasard ?

**Comment by VeroWWoof** [comment]
;) alors moi j'ai testé sur Firefox en me connectant sur son compte. Je viens d'essayer sur Chrome : idem ! Etrange ! 
<img width="1264" alt="capture d ecran 2015-08-19 a 10 25 28" src="https://cloud.githubusercontent.com/assets/12623351/9351807/a95e3250-465c-11e5-88e1-1efe7c4b3b91.png">

**Comment by gzurbach** [comment]
Aaah oui c'est ça ! La colonne de droite n'est **pas** visible si tu es connectée en tant que cet utilisateur. Pourquoi ? Simplement parce qu'un utilisateur qui veut voir à quoi ressemble son profil ne devrait pas voir les documents pour les hôtes. Si tu te connectes en tant que Virginie (ou n'importe qui d'autre) et que tu retournes sur ce profil tu verras les documents sans problèmes.

A noter cependant : si la taille de la fenêtre du navigateur n'est pas assez large la colonne de droite disparait aussi. Par exemple si tu visites cette page depuis une tablette ou un téléphone la colonne de droite sera invisible. C'est peut être ca qui est arrivé à ton hôte :)
