### ISSUE TITLE
INSCRIPTION SUR LA BASE OVH AU LIEU DE WORKBENCH

### ISSUE THREAD

**Issue by Virg-WF** [wwoof/webapp#179]
Salut Guillaume, j'ai encore un cas d'une personne ayant souscrit à l'assoc et qui apparait sur ovh et non sur workbench. Je vais lui recréer un compte sur workbench... bises. Pour info, il s'agit de DEMARLY LE MOAL EMMANUELLE emmanuelledemarly@yahoo.fr

**Comment by gzurbach** [comment]
On a fermé l'ancien site. Cela ne devrait plus arriver désormais.
