### ISSUE TITLE
act compte W

### ISSUE THREAD

**Issue by Virg-WF** [wwoof/webapp#181]
Suite à un bug (adh payé sur ppl mais compte non créer sur workbench) je suis allée sur workbench afin d'insérer une ligne WWOOFer ( puisque cette personne est déjà hôte) et malgré cela le compte ne s'active pas (je l'ai fait hier le 07/09 et ce matin tjs la même chose)
![2015-09-08_09-56-49](https://cloud.githubusercontent.com/assets/9193103/9729502/202ef7a8-5610-11e5-851d-a12fdf896355.png)
![2015-09-08_09-59-12](https://cloud.githubusercontent.com/assets/9193103/9729599/c5f3351e-5610-11e5-88e0-c183ba596133.png)
Sinon, afin que je puisse remplir au mieux les champs de workbench, en cas de bug, peux tu me dire où je trouve l'information concernant le paymentID & le payerID, stp ?

**Comment by gzurbach** [comment]
Dans la mesure du possible, il faut toujours éviter de passer par workbench pour rentrer des données dans le site. La seule exception est pour les adhésions (et même ça ce sera bientôt réglé).

La personne en question doit créer son profil de wwoofeur sinon l'adhesion ne sera pas prise en compte. Tu peux aussi te connecter en tant que cet utilisateur et créer son profil à sa place (cependant les champs motivations et introduction sont obligatoires).

<img width="623" alt="screen shot 2015-09-09 at 2 01 28 pm" src="https://cloud.githubusercontent.com/assets/795927/9761157/44f9a0c4-56fb-11e5-9997-315994ae80b5.png">

Le plus simple serait de dire a Camille de créer son profil wwoofeur elle-même et tout rentrera dans l'ordre.
