### ISSUE TITLE
DEMANDE DE NVEAU MOT DE PASSE

### ISSUE THREAD

**Issue by Virg-WF** [wwoof/webapp#182]
Salut Guillaume, 
Petite question : lorsque tu fais une demande de nveau mot de passe, celui que tu reçoit est-il provisoire ? Si tu ne le changes pas, peut-il bloquer le processus de connexion à ton profil, la fois suivante ? Merci, à bientôt...

**Comment by gzurbach** [comment]
Le mot de passe est "provisoire" dans le sens où les utilisateurs devraient probablement en choisir un autre une fois connectés (un dont ils peuvent se rappeler). Cela dit il peut être utilisé aussi longtemps que voulu, le compte ne sera pas bloqué.
