### ISSUE TITLE
Impossible de créer paiemnt adhésion nouvel hôte

### ISSUE THREAD

**Issue by alexxxxxxxxxxxxx** [wwoof/webapp#183]
aujourd'hui ça ne fonctionne pas... (cf pj)
![pah35](https://cloud.githubusercontent.com/assets/9049131/10016253/d63d2d24-6125-11e5-9881-8bef05872d19.png)

**Comment by gzurbach** [comment]
Pas de soucis. Je m'en occupe ce weekend !

**Comment by alexxxxxxxxxxxxx** [comment]
merci

**Comment by alexxxxxxxxxxxxx** [comment]
WARING WARNING
En fait, ça fonctionne c'est juste qu'il y a un message d'erreur mais le paiement est bien pris en compte ! :-D

Bon va juste falloir que je retrouve l’hôte pour lequel j'ai cliqué 40 000 fois en début de semaine... gloups

**Comment by gzurbach** [comment]
Ok je pense que ça devrait être bon maintenant. Dis-moi si ça se reproduit.
