### ISSUE TITLE
Nouvelle fonction

### ISSUE THREAD

**Issue by Virg-WF** [wwoof/webapp#184]
Je trouve ça super sauf peut être la recherche par nom... J'ai voulu trouver Patricia Gil pour faire son renouv et j'ai donc tapé Gil, mais elle n'est pas ressortie ds les premières pages, et vu le nombre de page, j'ai préféré faire une recherche avec son adresse email (malheureusement, on ne me la communique pas tjs). Bises. Virg.

**Comment by gzurbach** [comment]
Faut pas hésiter a chercher "Patricia Gil" directement :)

https://app.wwoof.fr/users?searchTerm=patricia%20gil

**Comment by Virg-WF** [comment]
alors moi j'avais noté Gil Patricia et ça n'avait rien donné.

**Comment by gzurbach** [comment]
La recherche se fait par prénom puis nom, pas l'inverse :)
