### ISSUE TITLE
Adhésion via le site

### ISSUE THREAD

**Issue by Virg-WF** [wwoof/webapp#185]
en faisant une adh en ligne pour une personne via le site, je me suis aperçue que des frais postaux venaient s'ajouter dans le total.
![2015-09-24_14-23-02](https://cloud.githubusercontent.com/assets/9193103/10073315/3d56da84-62c8-11e5-82d7-181ed5efb443.png)

**Comment by gzurbach** [comment]
Oups ! Pas de soucis, je m'en occupe ce weekend.

**Comment by gzurbach** [comment]
Je n'ai pas réussi a reproduire le bug. Est-ce que tu pourrais me donner la liste des étapes que tu as effectuées ?

**Comment by Virg-WF** [comment]
Je suis allée sur le site, j'ai cliqué sur "créer une nouvelle adhésion". J'ai ensuite choisi le type d'adhésion (à 25 = en igne solo)  ainsi que le mode de paiement et validé (puisque sur les livrets en ligne, tu ne peux pas choisir les frais de port). Du coup, je ne sais pas pourquoi les frais de port se sont ajouté... Peut être parce que ce sont des renouvellements ?

**Comment by Virg-WF** [comment]
ça vient  de se reproduire, voici les étapes faites : il s'agit de s.hoitsch@outlook.com (Sarah Hoitsch)
![2015-10-05_14-05-48-1](https://cloud.githubusercontent.com/assets/9193103/10280112/06f12ffc-6b6b-11e5-9912-31000f5ef8af.png)
![2015-10-05_14-06-41-2](https://cloud.githubusercontent.com/assets/9193103/10280115/0d67972c-6b6b-11e5-9a68-158616056018.png)
![2015-10-05_14-08-53-3](https://cloud.githubusercontent.com/assets/9193103/10280163/743ccbfc-6b6b-11e5-9723-83844ad3acc4.png)

**Comment by Virg-WF** [comment]
idem pour Berit Karlberg paiement espèce de 25 eur apparu à 29,56

**Comment by Virg-WF** [comment]
Nveau cas aujourd'hui : 	
![2015-10-15_14-05-32](https://cloud.githubusercontent.com/assets/9193103/10513162/ffb8abba-7345-11e5-8735-5b30530b4ea0.png)

le montant total est à 33 non plus à 29,56 comme les cas précédents.
Bises.

**Comment by Virg-WF** [comment]
Pour info : la personne concernée est Feruza Bayazitova, samantha-m@yandex.ru
Montant modifié par mes soins.

**Comment by Virg-WF** [comment]
ça le fait aussi pour les adhésion hôte, bises.
![Uploading 2015-10-23_10-04-56.png…]()

**Comment by gzurbach** [comment]
En attendant que je fixe ce bug est-ce que tu pourrais utiliser Chrome et me dire si ça se passe aussi avec ce navigateur ? Merci !
https://www.google.com/chrome/browser/

**Comment by Virg-WF** [comment]
OK, désormais j'utilise chrome et je te tiens au courant...

**Comment by Virg-WF** [comment]
![2015-11-05_10-06-41](https://cloud.githubusercontent.com/assets/9193103/10964321/c45e4914-83a6-11e5-9a4b-babe058636c2.png)

**Comment by gzurbach** [comment]
Bon cette fois-ci on devrait être bons. Je viens de faire une grosse mise à jour du site, rien de très visible tout est sous le capot. Cela devrait cependant régler ce problème définitivement.

La page ressemble désormais à ça:
<img width="881" alt="screen shot 2015-11-09 at 11 44 00 pm" src="https://cloud.githubusercontent.com/assets/795927/11056955/d3d2b9aa-873b-11e5-895a-a6c626d4302f.png">

Si ce n'est pas le cas pour toi rafraichit la page dans ton navigateur !

**Comment by Virg-WF** [comment]
super, mais par contre, on ne peuT plus faire d'act de compte Hôte !

**Comment by gzurbach** [comment]
Je ne comprends pas ce que tu veux dire. Est-ce que tu pourrais être plus spécifique ?

**Comment by Virg-WF** [comment]
Et bien, on ne voit plus les adhésions pour les hôtes (adh à 35 euros ou renouv à 30 euros). Celle qui sont affichées sont uniquement pour les WWOOFers, du coup, comment ça se passe si un hôte souhaite régler sa cotisation ?

**Comment by gzurbach** [comment]
Normalement rien n'a changé sur ce plan. 

Par exemple : https://app.wwoof.fr/memberships/new?itemCode=H&type=H&userId=83705

Tu vois les adhesions hôtes si tu es un hôte et les adhésions wwoofeur si tu es un wwoofeur.
