### ISSUE TITLE
Problème de paiement sur le site ?

### ISSUE THREAD

**Issue by VeroWWoof** [wwoof/webapp#188]
Hello Guillaume, 

Je pense qu'il y a un petit souci de paiement sur le site. 
J'ai commencé en milieu de semaine à recevoir 2 mails par ci par là de personnes ne comprenant pas pourquoi leur paiement n'était pas passé, je ne me suis pas inquiétée. Et puis depuis hier et ça continue today : des personnes qui ont un message d'erreur du site, les invitant à contacter le webmaster (tu en as peut être reçu ?). 

Quelques exemples : 
- mandarkpower@gmail.com (W sans aucune adhésion)
- chantaigut@bbox.fr (H pour qui après le 1er clic pour valider son paiement par CB a reçu le message d'erreur, a donc réassayé pensant faire une bêtise, idem, s'est finalement rendu compte qu'il avait bien eu 2 prélèvements. Virginie va lui en rembourser 1.
- florida.nor@gmail.com> : W qui a essayé de régler avec sa CB, impossible. Nous a donc envoyé un chèque
- Sylvie CASTANIER <ferme.equestre.de.berthaire@orange.fr> : H qui a tenté de régler 2 fois par CB le WE dernier, même bug du site. Elle aussi a fini par se rendre compte qu'elle avait été prélevée 2 fois, nous lui avons remboursée l'ahdésion de trop.

Bref, c'est bizarre ! 
Autre chose qui est peut être lié : ce matin j'ai voulu sur le site faire un paiement pour un hôte ( lesecureuils@mailoo.org)
<img width="1109" alt="capture d ecran 2015-10-16 a 12 35 15" src="https://cloud.githubusercontent.com/assets/12623351/10542568/56384b5c-7419-11e5-91bf-078a95c2a13a.png">
 qui nous avait adressé un chèque : au moment de cliquer sur valider l'adhésion : message d'erreur (cf pj), j'ai cliqué une seconde fois : idem. J'ai fini par retourner dans l'onglet adhésion de cet hôte et j'avais en fait appliqué 3 renouvellements. On les a supprimé ensuite avec Virginie dans WKB.

Voilà ! 

A ta dispo pour tout complément d'info.

Véro

**Comment by gzurbach** [comment]
Tous les problèmes liés aux hôtes ont été réglés. Pour ce qui est des wwoofeurs il y a de temps en temps des problèmes avec PayPal mais rien que l'on ne puisse faire vraiment. On en parle au prochain Skype.

**Comment by VeroWWoof** [comment]
Pour les hôtes concernés : le remboursement des doubles adhésions restent ils à faire ? merci !

**Comment by gzurbach** [comment]
Je n'ai fait aucun remboursement de mon côté donc il faudra voir avec
Virginie ou Alex si elles en ont fait.

Il faudra aussi supprimer les adhésions en double dans WB. Je me demande si
le plus simple ne serait pas d'écrire une requête SQL pour trouver les
doublons. On en parle au prochain Skype.

**Comment by VeroWWoof** [comment]
A nouveau des problèmes de paiements (visiblement liés à Paypal à présent) : 
Hôte : manjolive@gmail.com
W : Choo Wan Yee : muffincwy@hotmail.com

Merci !

V.

**Comment by VeroWWoof** [comment]
Autre problème de double paiement : Sabrina Duranceau <sabrinaduranceau@gmail.com> (WWOOFeuse)
"Bonjour,
Je vous contacte car je me suis inscrite en tant que woofeur le 22/10/2015...à ma première tentative de paiement m'a été indiquée que le transaction avait échoué...du coup j'ai recommencé cette dernière s'est faite avec succès.
Aujourd'hui sur mon relevé de compte, je constate 2 prélèvements paypal de 25€ chacun à 15 min d'intervalle..."

**Comment by Virg-WF** [comment]
Salut Guillaume, Des nveaux problèmes de double, voire triple paiements sont survenus en décembre...Pour info, il s'agit des adhérents n°85096 & n°72669

**Comment by gzurbach** [comment]
Je ferme tous les bugs liés à PayPal.
