### ISSUE TITLE
Envoyer une copie des messages hôtes aux wwoofeurs

### ISSUE THREAD

**Issue by Virg-WF** [wwoof/webapp#189]
Je reçois bcp de retour de WWOOFer qui me demandent où est ce qu'on peut trouver l'historique des emails envoyés, via le site ou simplement un historique des hôtes contactés... Ne peut on vraiment pas l'envisager ? Bises, Virg.

**Comment by Virg-WF** [comment]
Salut Guillaume, je relance le sujet car je reçois pas mal de mails concernant ce prob... Je pense que l'idée d'envoyer une copie de l'email envoyé à l'hôte et très bien... Bises.

**Comment by gzurbach** [comment]
Fixé !
