### ISSUE TITLE
BUG ou pas BUG ?

### ISSUE THREAD

**Issue by Virg-WF** [wwoof/webapp#190]
On a reçu un message d'un hôte ayant été approuvé et qui a effectué son paiement via Paypal et qui n'a pas été activé. Il s'agit de la ferme MANJOLIVE, Dalonis Sébastien <manjolive@gmail.com. Je l'ai act manuellement.
Je suis donc allée sur paypal pour vérifier son paiement et en effet, le paiement est ok. J'ai ainsi pu récupérer son numéro de transaction. J'ai donc lancé une requête sur workbench, dans la table memberships pour voir si ce num de trans était attribué et trouver l'userid pour le cas ou il y aurait une correspondance. J'ai donc réussi a retrouvé une personne associé à ce numéro de trans ppl mais qui ne correspond pas à l'hôte concerné. C'est un W, il s'agit de Théo Luyckx qui a prix son adh W le même jour que l'hôte, le 26 OCT. 
![2015-10-29_16-01-54](https://cloud.githubusercontent.com/assets/9193103/10822258/b5bc7cfa-7e56-11e5-9484-04c723e04122.png)

Est-il possible que le paiement  de Sébastien se soit ait été associé à une autre personne ou mon raisonnement est-il mauvais ?

**Comment by gzurbach** [comment]
Ca me semble vraiment **très** étrange mais je vais devoir investiguer cela ce weekend. Revoir tout le code et mettre au clair tous ces problèmes de paiement. Je te tiens au jus.

**Comment by Virg-WF** [comment]
Ok, ça marche. Bon courage...

**Comment by gzurbach** [comment]
Je ferme tous les bugs liés à PayPal.
