### ISSUE TITLE
2 moteurs de recherche = 2 affichages différents

### ISSUE THREAD

**Issue by Virg-WF** [wwoof/webapp#192]
Je suis allée sur chrome pour voir le nombre d'hôte présents sur l'île de la Réunion et ça m'a m'affiché deux fermes alors que sur firefox, j'en trouve 5, étrange non ?
![2015-11-03_15-28-34](https://cloud.githubusercontent.com/assets/9193103/10910555/40391252-8240-11e5-971d-ec5e3dd7e646.png)
![2015-11-03_15-29-14](https://cloud.githubusercontent.com/assets/9193103/10910558/4776b4b6-8240-11e5-9378-1a2f93ed6fc4.png)

**Comment by gzurbach** [comment]
Je ferme ce bug car j'ai réécris plusieurs fois cette page depuis que ça t'es arrivé. On peut espérer que ça ne se reproduira pas :)
