### ISSUE TITLE
Y at-il des prob avec le site aujourd'hui (10/11/2015) ?

### ISSUE THREAD

**Issue by Virg-WF** [wwoof/webapp#194]
Salut Guillaume, j'ai reçu plusieurs messages de WWOOFers encore bien  membres et qui n'avaient plus accès aux détails de contact. Bises, Virg.

**Comment by gzurbach** [comment]
Je viens de fixer le bug, cette fois-ci je le tiens bien ! Par contre comme de nombreux utilisateurs ont le site dans leur cache il se peut qu'ils nous contactent pendant plusieurs jours encore (max. 2-3 jours). Il faut que je me penche sur cette histoire de cache pour le configurer à 24h max sinon on aura ce genre de problèmes à chaque bug.

En tout cas tout remarche !
