### ISSUE TITLE
Profil H changements non pris en compte

### ISSUE THREAD

**Issue by alexxxxxxxxxxxxx** [wwoof/webapp#197]
Après avoir effectué des changements lorsque l'on clique sur "enregistrer", la confirmation du pavé vert en bas à droite n'apparait pas et effectivement les changements non plus... C'est super "embêtant" car je pensais que c'était quand même pris en compte (comme pour les paiements à un moment) mais non ; donc j'en ai fait pas mal mais ils n'ont pas été enregistrés...
HEEEEEEEEEEEEELP!

**Comment by gzurbach** [comment]
Désolé j'ai introduit un bug il y a quelques jours. C'est fixé maintenant. Pense à nettoyer le cache de ton navigateur si besoin.
