### ISSUE TITLE
Indiquer la durée de séjour des wwoofeurs

### ISSUE THREAD

**Issue by gzurbach** [wwoof/webapp#201]
Je travaille sur un prototype pour permettre aux hôtes de préciser les durées de séjour acceptables.

Ça ressemble à ça:
![screen shot 2015-12-02 at 6 08 20 pm](https://cloud.githubusercontent.com/assets/795927/11549958/ba7ad1ea-991f-11e5-8525-27d44ed82a3e.png)

Les wwoofeurs pourront bien entendu filtrer les hôtes par durée de séjour.

Je voulais savoir si:
 1. Les durées proposées vont bien
 2. On est OK sur le fait que par défaut toutes les durées seront cochées pour tous les hôtes, il faudra ensuite leur envoyer un email pour leur dire que cette fonctionnalité a été ajoutée et qu'ils peuvent ajuster.

Je pensais ajouter une case "Longue Durée" pour les hôtes qui cherchent des gens qui voudraient rester à ferme (employé du coup je suppose). Qu'est ce que vous en pensez ?

Voir exemple similaire ici : https://wwoofusa.org/our-farms/ (cliquer sur **Length of visit** à gauche dans les filtres)

**Comment by gzurbach** [comment]
L'idée derrière "1 Day (Local)" c'est de dire "je suis ok pour avoir des visiteurs pendant une journée mais je les héberge pas". Je pense que c'est bien pour les gens/familles du coin qui veulent aller visiter des fermes locales.

**Comment by VeroWWoof** [comment]
Hello ! 
Tout ça est une très bonne idée :) notre site est de plus en plus pro !! bravo !
Je trouve que les durées proposées sur le site US sont bien, sauf le côté "1 jour" : c'est, à mon avis, un peu "prématuré" pour l'organisation des hôtes en France (et serait un peu en décalage avec ce qu'on écrit partout sur le fait q'une semaine "minimum" c'est bien). Même si en soi, je trouve que ça serait top pour les 'locaux'. 
Et pour le "long terme", peut être une autre formulation ? " + lontemps" ? parce que tu as complètement raison : ça fait "employé" sinon et on se ferait dégommer
Merci encore !
Bises
V.
