### ISSUE TITLE
Indiquer le type d'hébergement offert par l'hôte

### ISSUE THREAD

**Issue by gzurbach** [wwoof/webapp#205]
Je pense que c'est vraiment la dernière donnée importante qui manque pour les hôtes : le ou les type(s) d'hébergement(s) qu'ils mettent à disposition des wwoofeurs.

Je pensais donc proposer :
 - Chambre dans la maison de l'hôte
 - Chambre dans un bâtiment séparé
 - Caravane / Camping-car
 - Tente (camping)
 - Yourte / Tipi
 - Cabane / Mobil-home

Les hôtes pourront cocher plusieurs options. Par défaut je ne cocherai rien, on les laissera mettre à jour leur profil eux-même.

Je ne suis pas sûr qu'il soit nécessaire de séparer "Chambre dans la maison de l'hôte" et "Chambre dans un bâtiment séparé", qu'est ce que vous en pensez ?

**Comment by VeroWWoof** [comment]
Hello ! Waaaouuuw :)  (y) 
Je suis d'accord avec toi pour la séparation de "chambre maison Hôte" et "chambre dans batiment séparé", on pourrait écrire : "chambre dans une maison" ?

**Comment by alexxxxxxxxxxxxx** [comment]
Merci, c'est super, ces infos là vont être appréciées !

On a re-reduit la liste pour éviter qu'il y ait trop d'infos sur la page 
•Chambre 
•Caravane / mobil-home
•Emplacement camping
•Yourte / Tipi / Cabane 

Merci bcp

**Comment by VeroWWoof** [comment]
Je vous partage un extrait de mail d'une W (je lui ai répondu) reçu sur Feedback :)

".... Les profils des hôtes sont bien, mais très souvent il manque des infos sur le logement. Ces infos sont déterminantes dans la toute première phase de sélection des hôtes, même avant de prendre contact avec eux ! ...Il faudrait peut-être les inciter à dire rapidement quel type de logement il proposent, par exemple en leur demandant de cocher quelques cases dans leur profil (logement dans une chambre/un dortoir/une caravane/yourthe chauffée/camping/ autre ??? )"

Merci

Véro.

**Comment by davidwwoof** [comment]
tu as repondu a la personne qui voulait son argent  car aucune réponse de notre part???

David Marie




www.wwoof.fr <http://www.wwoof.fr/>
http://www.facebook.com/pages/Wwoof-France/172038322894280 <http://www.facebook.com/pages/Wwoof-France/172038322894280>
Membre de l'association WWOOF International www.wwoofinternational.org <http://www.wwoofinternational.org/>

P Avant d'imprimer cet e-mail, réfléchissons à l'impact sur l'environnement. 
ECOSIA : le moteur de recherche écologique

**Comment by gzurbach** [comment]
Voila c'est fait ! Pour le moment pas possible de faire de recherche par type de logement offert car je n'ai rien mis par défaut. Il faudra donc attendre 2 mois environ que suffisamment d'hôtes aient saisi cette info avant de proposer un filtre sur ce critère.

Vous pouvez voir ce que ça donne ici : https://app.wwoof.fr/host/2124/edit

Je vais ouvrir un bug séparé pour la recherche.

**Comment by VeroWWoof** [comment]
Super :)

**Comment by gzurbach** [comment]
Pour info : j'ai ajouté "cabane" dans la liste, comme demandé :)

**Comment by alexxxxxxxxxxxxx** [comment]
;-) merci
