### ISSUE TITLE
Cohésion dans les dates affichées

### ISSUE THREAD

**Issue by Virg-WF** [wwoof/webapp#207]
Salut Guillaume ! pourrais tu, quand tu auras un moment, faire en sorte que la date dans "membre depuis..." qui apparait dans la fiche WWOOFer
![2015-12-07_12-35-22](https://cloud.githubusercontent.com/assets/9193103/11626102/6633a62e-9ce0-11e5-979d-73824636a5da.png) soit identique à la date du paiement qui apparait dans "mes adhésions" 
![2015-12-07_12-46-13](https://cloud.githubusercontent.com/assets/9193103/11626124/a06bd316-9ce0-11e5-9d93-8f071c98a46d.png), stp.

**Comment by gzurbach** [comment]
Afficher la date de première adhesion (hôte et wwoofeur) à la place de la date de création du profil.

**Comment by gzurbach** [comment]
Fixé !

**Comment by Virg-WF** [comment]
super, merci
