### ISSUE TITLE
Mauvais orthographe d'un département

### ISSUE THREAD

**Issue by alexxxxxxxxxxxxx** [wwoof/webapp#208]
"Dernier détail l'orthographe du département 35 est fausse : Ille et Vilaine (avec 2 L SVP)"

merci

**Comment by gzurbach** [comment]
Fixé ! 

Est-ce qu'on devrait remplacer 'Paris' par 'Île-de-France' aussi ?

**Comment by alexxxxxxxxxxxxx** [comment]
Excellente réflexion ! GO

**Comment by gzurbach** [comment]
En fait "Île-de-France" c'est la région. Le département du 75 c'est bien Paris.

**Comment by alexxxxxxxxxxxxx** [comment]
je sais...
