### ISSUE TITLE
Photos téléchargées mais invisibles pour l'Hôte

### ISSUE THREAD

**Issue by alexxxxxxxxxxxxx** [wwoof/webapp#209]
Je vois bien pourtant, moi, les photos téléchargées....
J'ai aussi qqles mails avec le même prb mais pour les adhésions, les paiements sont faits mais apparemment on leur redemande... Je ferai un autre github pour ça ;-)

Leroy Vladimir <leroy.vlad@gmail.com>
"Bonjour,
Je me suis récemment inscrit sur le site du wwoofing France en temps qu'hôte.
Je n'arrive pas à incorporer des photos à mon profile, lorsque je clic sur parcourir et que j'ouvre une photo sur mon ordinateur, la barre de téléchargement avance et écris 100%. Cependant rien ne se passe et il est écris "aucun fichier séléctionner". Mes photos font moins de 5 Mo, elle font 60 Ko.
Avez vous une solution ? 
Merci par avance,
Vladimir"

**Comment by gzurbach** [comment]
Fixé !

**Comment by gzurbach** [comment]
Note : j'ai aussi fixé le problème pour les adhésions dans la foulée.
