### ISSUE TITLE
Plus possible de prendre une nouvelle adhésion pour un W

### ISSUE THREAD

**Issue by VeroWWoof** [wwoof/webapp#212]
Hello, 
Suite à un mail d'un W (annasawall@web.de) ce matin se plaignant de ne pas trouver le moyen de payer son adhésion, je suis allée, ainsi que Virginie, vérifier sur le site et effectivement le lien "créer une nouvelle adhésion" n'est plus visible pour cet utlisateur. Cf PJ
Merci :)
<img width="1241" alt="capture d ecran 2015-12-17 a 12 31 55" src="https://cloud.githubusercontent.com/assets/12623351/11868712/354f09e0-a4ba-11e5-996f-704b21cab1de.png">

**Comment by gzurbach** [comment]
Aucun bug, Anna n'a pas terminé la création de son profil : il manque l'adresse.

Elle doit aller ici : https://app.wwoof.fr/wwoofer/72452/address

Bises!
