### ISSUE TITLE
Y at-il des prob avec le site aujourd'hui (04/01/2016) ?

### ISSUE THREAD

**Issue by Virg-WF** [wwoof/webapp#215]
Salut Guillaume, il semblerait qu'il y ait qlq petits soucis avec le site, car je n'arrive à me connecter, c'est la page blanche. J'ai testé avec chrome et firefox et c'est la même chose. Bises.

**Comment by alexxxxxxxxxxxxx** [comment]
Pareil pour moi, ça a commencé à devenir "bizarre" en fin de matinée

**Comment by VeroWWoof** [comment]
Idem chez moi ! Biz ;)

**Comment by gzurbach** [comment]
Fixé... j'avais laissé un petit bug derrière moi avec les derniers changements.

**Comment by Virg-WF** [comment]
super, ça fonctionne ! Merci...
