### ISSUE TITLE
Changt frais postaux

### ISSUE THREAD

**Issue by Virg-WF** [wwoof/webapp#216]
Nouvelle année oblige, les frais postaux ont augmentés !
Pour la France : 4,80, l'Europe : 8,35 et l'international : 11,45
Pour l'outremer 1: 8,55 et l'outremer 2 : 13,05
Peux-tu les modifier quand tu auras un moment, stp ?

**Comment by Virg-WF** [comment]
Pourras-tu t'en occuper prochainement ?

**Comment by gzurbach** [comment]
Oui j'ai pas oublié t'inquiète !

**Comment by alexxxxxxxxxxxxx** [comment]
Du coup vu que tu es dans les modifs de frais 42 pour solo avec livret et 47 pour duo avec livret ?
Dis-moi quand ce sera fait que j'actualise le site...
Merci.

**Comment by gzurbach** [comment]
Voila voila c'est fait !

Pensez à jeter un coup d'oeil et dites-moi ci ça a l'air bon : https://app.wwoof.fr/memberships/new?itemCode=WO1&type=W

**Comment by Virg-WF** [comment]
Super, merci Guillaume !

**Comment by alexxxxxxxxxxxxx** [comment]
Je confirme : un immense merci ;-)
