### ISSUE TITLE
Modifier le texte du mail qui informe l'hôte d'un message WWOOFeur

### ISSUE THREAD

**Issue by VeroWWoof** [wwoof/webapp#217]
Hello, 
Chaque semaine, je reçois sur hello@wwoof.fr, qq mails d'hôtes qui répondent directement à hello@ plutôt qu'au WWOOFeur.
Le mail qui informe l'hôte qu'un W leur écrit dit " ...Vous avez reçu un message de Dupont Dupont via le site WWOOF France. Vous pouvez répondre à cet email ou contacter directement xx@ccc.fr"
Il serait peut être bon d'enlever le texte "Vous pouvez répondre à cet email ou" et le remplacer par "Vous pouvez répondre directement à xx@ccc.fr" ? tu en dis quoi ?
Merci :D 
Bises
V.

**Comment by gzurbach** [comment]
Note pour moi-même : http://stackoverflow.com/questions/2231897/potential-issues-using-members-from-address-and-the-sender-header

A implementer !

**Comment by gzurbach** [comment]
Bonne nouvelle ! Le problème est réglé.

J'ai créé une nouvelle adresse (messaging@wwoof.fr) que j'utilise désormais à la place de hello@wwoof.fr pour envoyer les messages des wwoofeurs aux hôtes. 

Cette adresse email a une réponse automatique si quelqu'un essaye de répondre. Je vous invite donc à envoyer un email à messaging@wwoof.fr pour vérifier que ça vous convient. Si besoin de changer, allez sur OVH et éditez le message du répondeur.

Je vais aussi créer une adresse noreply@wwoof.fr pour les autres emails (création de compte, changement de mot de passe, etc.) dans les jours qui viennent. Cette adresse aura un autre répondeur mais plus générique cette fois.

**Comment by alexxxxxxxxxxxxx** [comment]
super ! Je change un petit truc mais c'est par-fait, merci.
