### ISSUE TITLE
Erreurs dans le classement des départements/régions

### ISSUE THREAD

**Issue by VeroWWoof** [wwoof/webapp#220]
Hello :)
Je me suis aperçue d'une petite erreur sur les régions Midi-Pyrénées / Languedoc Roussillon et PACA : les départements GARD (30) et LOZERE (48) ne sont pas rattachés à "Midi-Pyrénées / Languedoc Roussillon" mais à PACA, dans la nouvelle nomenclature des régions.

Merci :)

Véro

**Comment by gzurbach** [comment]
Pourrais-tu m'envoyer une copie d'écran du bug ? Je viens de vérifier dans la base de données et sur le site et il semble que tout est en ordre :)

<img width="364" alt="screen shot 2016-01-27 at 11 52 41 pm" src="https://cloud.githubusercontent.com/assets/795927/12638368/6d9cc8ac-c551-11e5-8fa2-edcab152daae.png">

<img width="354" alt="screen shot 2016-01-27 at 11 52 31 pm" src="https://cloud.githubusercontent.com/assets/795927/12638370/700e80e4-c551-11e5-8e69-9e7cdf801398.png">

**Comment by VeroWWoof** [comment]
Excuse moi : c'était l'inverse en fait que je voulais dire O.o 
Ces 2 départements doivent être attachés à PACA (et non Midi Pyrénées).
Merci :)
Bises

**Comment by gzurbach** [comment]
Je viens de la région PACA et il me semble bien que rien n'a changé pour nous. 

Voici la carte : http://www.cartesfrance.fr/cartes/geographie/carte-13-nouvelles-regions.jpg

**Comment by gzurbach** [comment]
Je ferme ce bug car je pense que tout est en ordre. N'hésite pas à réouvrir si je me suis trompé.
