### ISSUE TITLE
Prob avec le paiement d'une adhésion

### ISSUE THREAD

**Issue by Virg-WF** [wwoof/webapp#221]
Salut Guillaume,
J'ai voulu activer un compte W en procédant au paiement de l'adhésion et il se trouve,en fait, que c'est le compte du précédant W qui a été activé de nouveau : je m'explique.
Recherche du W dans  utilisateur, je clique sur adhésion, car je souhaite vérifier son adresse postale 
![2016-01-27_11-05-29](https://cloud.githubusercontent.com/assets/9193103/12610064/ef579154-c4e5-11e5-9789-0d6a905d3c20.png) 
puis sur, mon adresse et là comme tout est en règle, je décide de cilquer sur "payer mon adhésion" 
![2016-01-27_10-58-11](https://cloud.githubusercontent.com/assets/9193103/12610124/38674ca4-c4e6-11e5-934a-e9e8d9ea1b47.png)
Et là, étrangement je me retrouve sur le compte du précédent WWOOFer, que j'ai enregistré, et du coup, si je clique sur "créer l'adhésion" il se retrouvera avec une adhésion pour deux ans !
![2016-01-27_11-12-20](https://cloud.githubusercontent.com/assets/9193103/12610243/e62377dc-c4e6-11e5-93f1-ce68e5b6c0ae.png)

**Comment by gzurbach** [comment]
Hmm je n'ai pas tout compris mais garde ça bien au chaud pour le prochain Skype et tu me ré-expliqueras en détails :)

**Comment by Virg-WF** [comment]
ok, pas de prob on en reparle au proch skype...

**Comment by gzurbach** [comment]
Pas de reproduction possible. 

Je ferme pour le moment jusqu'à ce qu'on puisse identifier une méthode de reproduction.
