### ISSUE TITLE
Critères de recherche pour hôte

### ISSUE THREAD

**Issue by VeroWWoof** [wwoof/webapp#222]
Hello, 
J'ai reçu ce matin de panoramane@hotmail.com un hôte qui se "plaignait" (très gentiment) de ne pas se voir apparaître dans le résultat des hôtes avec son nom de ferme : "Panoram'âne". 
Je vérifie : aucun résultat... Je cogite 3 min avec d'aller vérifier sur sa fiche ce qu'il a renseigné à "nombre de W". Il a sélectionné "2 W". Je pense qu'il a compris à juste titre : "je peux héberger jusqu'à 2 W" 
Du coup, pourquoi ceux qui ont sélectionné "je peux héberger jusqu'à 2, 3 ou 4 W" n'apparaissent ils pas dans les résultats de recherche pour 1 W ? sachant que s'ils peuvent en recevoir jusqu'à 2, 3 ou 4 c'est bien qu'ils peuvent en recevoir 1 :D 
Je ne sais pas si je suis très claire ;) si non, n'hésite pas.
Des bécots
V.

**Comment by gzurbach** [comment]
Qu'est ce que tu as saisi dans la recherche pour trouver cet hôte ?

Normalement si tu mets "1 wwoofeur" les hôtes avec 2 wwoofeurs apparaissent.

**Comment by gzurbach** [comment]
Ok je viens de comprendre : c'est pas sur le nombre de wwoofeurs que ça coince, c'est sur la durée du séjour. Il ne propose pas '1-2 semaines' mais uniquement '3-4 semaines' ou '> 1 mois'. Par défaut c'est 1-2 semaines qui est saisi.

**Comment by gzurbach** [comment]
Je viens de changer le comportement des filtres. Par défaut aucune durée de séjour n'est sélectionnée donc tous les hôtes apparaissent.

Donc de ça :
<img width="737" alt="screen shot 2016-02-07 at 6 24 28 pm" src="https://cloud.githubusercontent.com/assets/795927/12877439/28e22b88-cdc8-11e5-9a79-647429afb2a6.png">

On est passé vers ça :
<img width="738" alt="screen shot 2016-02-07 at 6 24 46 pm" src="https://cloud.githubusercontent.com/assets/795927/12877443/389b6288-cdc8-11e5-9aec-069eb1b704c2.png">

Sur 1195 hôtes actifs on en a 1155 qui ont coché "1-2 semaines" donc les chances que cette confusion arrive était faible !

**Comment by VeroWWoof** [comment]
;) super merci M'sieur (y)
