### ISSUE TITLE
Bug avec Paypal ?

### ISSUE THREAD

**Issue by VeroWWoof** [wwoof/webapp#225]
Hello, 
J'ai reçu qq mails depuis hier signalant des problèmes de paiement avec PPL. Je viens de collecter ces 2 adresses emails pour exemple  

lola_xxxx@hotmail.com ("La page Pay pal ne me valide absolument rien et reste sur la page de paiement...")
nicole.xxxx@laposte.net

Merci !

Bises

Véro

**Comment by VeroWWoof** [comment]
Problème de double paiement avec PPL : Manou <manou.dubost@wanadoo.fr>

**Comment by gzurbach** [comment]
Tout semble marcher correctement. Je viens de vérifier, il y a eu une vingtaine de paiements aujourd'hui. Probablement un bug temporaire avec PayPal mais rien qui soit de mon ressort.
Pour le double paiement il faut simplement le supprimer dans la base. Si tu as besoin d'indications sur comment faire demande-moi sur Skype :)

**Comment by VeroWWoof** [comment]
:) merci ! 
Je sais faire dans Workbench ;) elle devra juste attendre que Virginie soit de retour !
Merci
Des bécots

**Comment by gzurbach** [comment]
Je voulais dire dans Workbench pardon (dans la base = dans Workbench).
Bises :)

**Comment by VeroWWoof** [comment]
oui :) 
Entre temps hier : mon Keepass a "explosé" en vol = je n'ai plus aucun mot de passe mais bon O.o !! Je disais attendre le retour de Virginie pour le remboursement via PPL (auquel je n'ai pas accès)
Encore merci :D Bises
