### ISSUE TITLE
Requête pour hôtes approuvés n'ayant pas réglé leur adhésion

### ISSUE THREAD

**Issue by VeroWWoof** [wwoof/webapp#226]
Comme convenu, j'aimerais donc envoyer un mot aux hôtes dont on a approuvé le profil mais dont l'annonce est inactive du fait qu'ils n'aient pas payé. 
Aussi, peux tu me créer une requête indiquant
- date d'approbation
- adresse email
- nom de la ferme

Merci :)

Véro

**Comment by gzurbach** [comment]
Voila c'est fait ! La view s'appelle `vero_hotes_approves_sans_adhesion`.

Je t'ai mis le téléphone aussi au cas où :)

**Comment by VeroWWoof** [comment]
merci tu es un chou :D je vais aller voir cela ;)
