### ISSUE TITLE
Bug : mauvais hôte qui répond (??)

### ISSUE THREAD

**Issue by VeroWWoof** [wwoof/webapp#227]
Hello, 
Ci-dessous l'email d'un internaute. As tu une idée ? ou bien se trompe t il vraiment ? :)
Merci !
Bises
V.

**
"Bonjour,
Il m'est arrivé quelque chose d'étrange hier sur votre site, que je voulais vous signaler. Je pense que c'est un bug de votre site.
Huer soir, nous avons écrit a cette ferme pour être hébergés en tant que wwoofeurs : https://app.wwoof.fr/host/2774.
Ce matin, nous avons reçu une réponse d'une autre ferme, celle-ci : https://app.wwoof.fr/host/2047.
Je suis persuadé d'avoir écrit à la première, et pense qu'il y a eu un bug dans votre site (mais l'erreur est humaine, je peux me tromper).
Bonne journée,
François 
Ps : nous allons nous arranger avec les 2 fermés en question, ne vous inquiétez pas ! :-)"
**

**Comment by gzurbach** [comment]
Très peu probable. Rien n'est impossible en informatique donc je ne dis pas ce n'est pas possible. Mais si c'était un problème recurrent on en entendrait parler plus souvent.

Je ferme pour le moment, on rouvrira au besoin.
