### ISSUE TITLE
Ajout case écoconstruction

### ISSUE THREAD

**Issue by alexxxxxxxxxxxxx** [wwoof/webapp#228]
Dans la liste des activités proposées peut-on ajouter écoconstruction TOUT en sachant que si seule cette case est cochée une petit fenêtre WARNING s'ouvre en rappelant que cette activité est un plus mais qu'elle ne peut à elle seule suffire pour devenir Hôte ?
Merci.

**Comment by alexxxxxxxxxxxxx** [comment]
Est-ce qu'on pourrait revenir sur ça d'ici quelques temps ?

**Comment by gzurbach** [comment]
Fait !
