### ISSUE TITLE
Liens dans "mail bienvenue Hôte" HS ?

### ISSUE THREAD

**Issue by VeroWWoof** [wwoof/webapp#230]
Hello, 

Apparemment les liens suivants, envoyés dans le mail de bienvenue à un nouvel hôt,e sont HS et renvoient vers une erreur "404". Je les ai tous cliqués, aucun ne fonctionne ! Bawk bawk !
•	Déclaration wwoofeur 
•	Charte du wwoofing 
•	Règlement intérieur 
•	Comment sélectionner vos wwoofeurs ? 
•	L'arrivée du wwoofeur 

Cela nous a été signalé par magali solal <las-peyras@orange.fr> mais son mail de bienvenue date de mi novembre dernier, c'est peut être pour cela ?

Merci
Bises

V.
![bug](https://cloud.githubusercontent.com/assets/12623351/13631074/fd3e2724-e5e2-11e5-919b-ab621f1d3cd2.png)

**Comment by gzurbach** [comment]
Oui les liens ont changé. J'ai bien mis à jour l'email donc il n'y a pas de bug. Pour cet hôte il doit simplement remplacer `www.wwoof.fr` par `docs.wwoof.fr` dans l'URL et ça devrait marcher.

Malheureusement on n'a pas pu conserver les liens avec le nouveau site...
