### ISSUE TITLE
Ajouter n° d'urgence sur profil W

### ISSUE THREAD

**Issue by alexxxxxxxxxxxxx** [wwoof/webapp#231]
"Ce qu’il faudrait surtout c’est que lors de l’inscription d’un WWOOFeur, les coordonnées d’une personne à contacter en cas d’urgence soir renseignées. Comme ça, dans l’éventualités d’un gros soucis, l’hôte chez qui est le WWOOFeur ou l’association peuvent contacter directement cette personne d’urgence. Il faudra cependant mettre en avant que ce numéro ne sera utilisé que dans le cas ou le wwoofeur a un soucis, pas dans d’autres cas.
Alex va créer un ticket github pour ça."

merci

**Comment by gzurbach** [comment]
C'est fait !
