### ISSUE TITLE
compte W actif, sans trace de paiement sur PPL

### ISSUE THREAD

**Issue by Virg-WF** [wwoof/webapp#232]
Salut Guillaume,
Je suis face à un mystère… j'ai trois comptes actifs en janvier, dont les paiements ont visiblement été effectué via PayPal (source Workbench), avec numéro de transaction pour chacun (5U874450UW8007634, 0K783749SU009243F, 4TA86279DV2476748). Seul problème, ces numéros de transaction n'apparaissent pas sur le relevé PayPal de janvier (ni sur les autres d’ailleurs) et lorsque je lance une recherche, aucun résultat trouvé ! Idem avec la recherche par nom et adresse email... Du coup je me demande s'il n'y a pas eu un bug... D'après WORKBENCH, ces transactions ont eu lieu le 08/01. J’ai vérifié les paiements reçus par chq, esp et virt, pas de trace…  Est-il possible qu’un numéro de transaction ait été attribué sans que le paiement ait été fait au préalable?
Bises, Virg.

**Comment by Virg-WF** [comment]
Salut Guillaume, 
Enfin un retour de la part d'un des trois WWOOFeur ! Roulement de tambour... 
C'est dû à un bug Paypal ! Voici le mail reçu par la WWOOFeuse :

---------- Message transféré ----------
De : PayPal <paypal@paypal.com>
Date : 14 janvier 2016 à 20:09
Objet : Votre transaction PayPal a été rejetée par erreur.
À : julyette.chevalier@gmail.com

 	 	Votre transaction PayPal a été rejetée par erreur.

Bonjour Juliette Chevalier,

Les 7 et 8 janvier, PayPal a rencontré un problème technique qui vous a empêché d'effectuer une transaction. En effet, durant cette période, vous avez essayé d'effectuer un paiement ou un achat, mais notre système a rejeté la transaction par erreur. Vous avez ensuite reçu un email indiquant, à tort, que la transaction avait été rejetée parce que votre compte avait excédé la limite de paiement avec PayPal. 
Votre compte a bien une limite de paiement, mais la transaction de la semaine dernière n'a pas dépassé cette limite. Nous avons corrigé ce problème, et nous vous prions de nous excuser pour la gêne occasionnée. 
Si vous souhaitez en savoir plus sur la limite de paiement de votre compte ou savoir comment augmenter cette limite, connectez-vous à votre compte PayPal et suivez ensuite les étapes indiquées. 
Si vous avez besoin d'aide, cliquez sur le lien Contact sur n'importe quelle page du site PayPal pour nous contacter par téléphone ou par email. 
Merci d'avoir choisi PayPal. 
	 

	 

 	 	 	 	 	 	 

 
Merci ne pas répondre à cet email. Les messages reçus à cette adresse ne sont pas lus et ne recevront donc aucune réponse. Vous avez d’autres questions ? Vous trouverez toutes vos réponses en cliquant sur le lien Service Clientèle en bas de chaque page PayPal.

Copyright © 2016 PayPal. Tous droits réservés. PayPal (Europe) S.à r.l. et Cie, SCA, Société en commandite par actions. Siège social: 22-24, boulevard Royal, L-2449, Luxembourg, RCS Luxembourg B 118 349.

**Comment by gzurbach** [comment]
Je ferme tous les bugs liés à PayPal.
