### ISSUE TITLE
Ajouter un bouton "contacter le wwoofeur"

### ISSUE THREAD

**Issue by VeroWWoof** [wwoof/webapp#234]
Hello :)
A la demande de 2-3 hôtes cette semaine, qui nous ont contacté par mail et tel, est il possible de faire réapparaitre les adresses emails des WWOOFeurs pour les hôtes ? 
Merci
V.

**Comment by gzurbach** [comment]
Salut Vero,

Est-ce que tu sais pourquoi les hôtes ont besoin des emails de wwoofeurs ? Sachant que les hôtes sont contactés directement par les wwoofeurs et ils devraient déjà avoir leur email, non ?

Ça m'embête un peu de montrer les emails de tout le monde, surtout après les ennuis qu'on a eu.

**Comment by alexxxxxxxxxxxxx** [comment]
j'ai eu la même question 2-3 fois. mais effectivement ce sont les WWOOFeurs qui contactent les H et non l'inverse... Devons-nous mieux expliquer ceci aux H ou faire réapparaître les emails ?

**Comment by gzurbach** [comment]
OK je vois. On discute de ça au Skype du coup.

**Comment by VeroWWoof** [comment]
Bonne idée le changement de "titre" :)

**Comment by alexxxxxxxxxxxxx** [comment]
Salut,
Ci-dessous un bon exemple, le choix ne va pas être facile...
"Bonjour,
oui je lisais quelques profils au hasard, je retenais surtout ceux qui semblaient s'interesser à l'agriculture paysanne ou avec qui il pouvait y avoir des choses à partager. Par exemple aux vacances de la toussaint j'ai accueilli une famille, parents et deux enfants, j'avais aimé leur présentation et lui était musicien. Après quelques échanges par mail, j'ai compris qu'il faisait de la percussion corporelle, exectement ce que l'on cherchait à introduire dans notre spectacle (je chante dans un groupe de polyphonie). Leurs filles avaient des âges proche des miennes... Ils sont restés quelques jours et ça a été très sympa. Quelques mois plus tard le hasrd a fait que nous allons faire la première partie de son groupe de musique! 
J'ai aussi contacté un jeune de 18 ans dont le texte de présentation me semblait particulièrement mature et correspondre à ce que j'ai envie de partager: ce qu'est l'agriculture paysanne. Il est resté deux semaines et autant pour lui que pour nous ce fut une belle expérience, il dit qu'il est venu parce que je l'avais contacté.
Lorsque ce sont des woofeurs qui me contactent, c'est aussi une rencontre mais je me rend compte que je transmet moins ce qui me passionne de transmettre, le sens de mon métier, car ce n'est pas cela qu'ils viennet chercher. Je veux bien être une étape de vacances mais j'aime bien que ce soit un peu plus.
Voilà pourquoi il m'est arrivé de contacter des woofeurs.
Elisa"

**Comment by alexxxxxxxxxxxxx** [comment]
Salut, encore un message. Je trouve que ça devient inquiétant ; peut-on faire marche arrière ?

"bonjour, je ne reçois aucune demande de wwoofing malgré mon adhésion et je ne peux pas inviter de wwoofeurs; les seules demandes que j'ai reçu viennent de mon post sur le FB de wwoof france ; ce sont des personnes qui en sont pas adhérentes ; il y a ainsi tout un circuit qui se développe parallèlement ; c'est vraiment dommage de ne plus avoir accès aux mails des wwoofeurs et je ne sais pas si je vais maintenir mon adhésion ; 
voici pour la suite ds informations;
cordialement, gabriel "

Même si pour moi le circuit // n'a rien à voir avec ça.
Merci

**Comment by gzurbach** [comment]
Voilà c'est bon ! Les wwoofeurs peuvent maintenant être contactés par les hôtes.

Par exemple : https://app.wwoof.fr/wwoofer/82181 (voir bouton à droite)

**Comment by gzurbach** [comment]
PS : pensez à contacter les hôtes pour leur dire que c'est désormais possible.
