### ISSUE TITLE
Recherche hôte infructueuse

### ISSUE THREAD

**Issue by alexxxxxxxxxxxxx** [wwoof/webapp#235]
le 3318 ne se retrouve pas (et moi non plus) lorsqu'on entre haute-Marne, potager, cueillette etc..., merci.

**Comment by gzurbach** [comment]
C'est normal que tu ne le trouves pas dans la Haute-Marne vu que cet hôte est dans la Haute-Saône :) 

Aussi, note que la recherche en texte libre ne se fait que sur 4 champs : nom de l'hote, nom de la ferme, description ou ville.

Le department n'est plus dans la recherche en texte libre car c'est trop compliqué. C'est pour ça que j'ai mis un filtre par département.

Pour les activités c'est pareil : il faut utiliser les cases à cocher, pas la recherche libre.

Tout semble donc marcher pour moi : https://app.wwoof.fr/hosts?activities=%5B%22foraging%22%2C%22vegetables%22%5D&dptId=71&lat=47.76332998647307&lon=5.51788330078125&searchTerm=sustainable&showMoreFilter=true&zoom=8
