### ISSUE TITLE
déclaration hôte

### ISSUE THREAD

**Issue by Virg-WF** [wwoof/webapp#236]
J'ai eu l'occasion de discuter avec un hôte ce weekend et celui-ci cherchait à imprimer la déclaration, mais ayant perdu/supp son mail de bienvenue contenant ce document, difficile... Il faudrait, je pense,  les mettre à dispo sur le profil des hôtes pour qu'ils puissent  y avoir accès facilement.
Bises.

**Comment by gzurbach** [comment]
La déclaration est déjà disponible en téléchargement sur chaque profil wwoofeur, à droite, si tu te connectes en tant qu'hôte.

Je pense que vous pourriez la mettre aussi sur le site public (www.wwoof.fr) dans une page "documents utiles" ou quelque chose comme ca.
