### ISSUE TITLE
Candidature H introuvable dans la liste

### ISSUE THREAD

**Issue by alexxxxxxxxxxxxx** [wwoof/webapp#240]
Cet H a posé sa candidature mais je ne la trouve pas dans la liste.
Lorsque je me connecte avec son mail j'ai les infos suivants (cf capture) O-O
Ses coor ne sont pas renseignées, est-ce que le bug vient de là ? 
Ou bien l'étrangeté de son texte a t'il tout déréglé
[Uploading CandH.docx…]()
 ;-)

**Comment by gzurbach** [comment]
Problème résolu : l'hôte n'avait pas complété son profil.
