### ISSUE TITLE
Ne pas montrer de notification pour les 404

### ISSUE THREAD

**Issue by VeroWWoof** [wwoof/webapp#241]
Un W nous signale qu'à chaque connexion, il voit apparaitre des messages d'erreur (voir PJ). Cela ne l'empêche pas a priori de surfer et mettre des H en favoris...etc mais le gêne un peu :)
Son email est : jekelleher93@yahoo.co.uk
Dans un 1er temps je suis allée checker son profil (en tant qu'admin) : tout semble pourtant correct
Ensuite, je me suis connectée avec son mail et effectivement les dits messages apparaissent. 
Merci
Bises
Véro
![image](https://cloud.githubusercontent.com/assets/12623351/14354832/171fd472-fcdf-11e5-813c-be652ab4d822.jpg)

**Comment by gzurbach** [comment]
Je sais d'où ca vient, ce sera facile à régler.

**Comment by VeroWWoof** [comment]
(y)

**Comment by gzurbach** [comment]
Fixé.
