### ISSUE TITLE
erreur même si hebergement renseigné

### ISSUE THREAD

**Issue by alexxxxxxxxxxxxx** [wwoof/webapp#244]
[capture.docx](https://github.com/wwoof/webapp/files/212933/capture.docx)
Même si infos renseignées j'ai tjs un message d'erreur pour cet H
https://app.wwoof.fr/host/669/edit

**Comment by gzurbach** [comment]
Je confirme qu'il y a bien un bug. Si tu coches et décoches les cases plusieurs fois tu verras le rouge fini par disparaitre et tu peux sauvegarder ses infos.

Je fixerai ça au plus vite.

**Comment by alexxxxxxxxxxxxx** [comment]
oui je m'en suis rendue compte au fil de la journée et je fais comme ça. Merci !

**Comment by gzurbach** [comment]
Fixé !
