### ISSUE TITLE
Liste des Hôtes n'ayant PAS été mis en FAVORIS

### ISSUE THREAD

**Issue by alexxxxxxxxxxxxx** [wwoof/webapp#247]
Désolée, ce n'est pas un bug mais ça urge car c'est la saison et ton idée est excellente !
Mais nous avons réfléchi trop vite l'autre fois car pour mettre un hôte en avant, c'est plutôt celui qui n'est jamais mis en favoris que nous devrions prendre.
Revoir son texte, vérifier qu'il a bien coché les cases Activités etc...
Peux-tu nous faire une requête pour ça ? C'est à dire la wiew Hotes-de-la-semaine whitout count.
Merci

**Comment by gzurbach** [comment]
Si tu prends la requête hote_de_la_semaine les hôtes sont triés par nombre de favoris. Donc si tu descends en bas de la liste tu as ce que tu cherches :)

Attention : tous les hôtes sont dans cette liste, même ceux qui ne sont plus membres ou qui sont cachés ou exclus.

**Comment by alexxxxxxxxxxxxx** [comment]
mais il n'y a pas de chiffre "0" le plus petit est "1". 
Où sont ceux qui n'ont jamais été mis en favoris ? Ou alors ils ont tous au moins une fois été mis en favoris... ?
Sinon pas très grave si il y a les obsolètes et les exclus etc.. on vérifiera ça ;-)

**Comment by gzurbach** [comment]
Ok j'ai supprimé la vue `hote_de_la_semaine` et remplacé par une nouvelle vue `hotes_par_popularite`. Il y a les 0 dedans. J'ai aussi filtré tous les non-membres, non-visibles, etc. On a donc 1312 hôtes dans cette liste.

Je ne sais pas pourquoi mais les 0 et les 1 se mélangent un peu en bas de la liste. Probablement un bug de Workbench mais c'est pas trop gênant.

**Comment by alexxxxxxxxxxxxx** [comment]
t'es trop fort, merci beaucoup ;-)
