### ISSUE TITLE
Inscription H impossible

### ISSUE THREAD

**Issue by alexxxxxxxxxxxxx** [wwoof/webapp#249]
J'ai reçu 2 mails ce matin.
Impossible de terminer son inscr H car les champs logement + nbr WWOOFers même renseignés ne sont pas pris en compte et empêchent le passage
[cature.docx](https://github.com/wwoof/webapp/files/218907/cature.docx)
 à l'étape suivante.
J'ai reproduit le bug, cf capture.

**Comment by gzurbach** [comment]
Fixé. Désolé j'ai vraiment fait n'importe quoi avec cette validation.

**Comment by alexxxxxxxxxxxxx** [comment]
Rapide ! Merci ;-)
