### ISSUE TITLE
Ajouter case à cocher pour photo hôte

### ISSUE THREAD

**Issue by alexxxxxxxxxxxxx** [wwoof/webapp#250]
Ajouter une case afin que l'hôte puisse choisir qu'elle photo il souhaite voir apparaître en premier sur son profil, merci.

**Comment by gzurbach** [comment]
C'est fait ! merci de jeter un coup d'oeil pour confirmer que tout marche bien :)

**Comment by alexxxxxxxxxxxxx** [comment]
Ça marche nickel ! Merci pour cette nouvelle amélioration.
J’ai eu deux cas la semaine dernière où j’ai dû « retailler » plus remettre dans l’ordre au moins 8 photos.

Je reste à votre disposition, bonne journée.

Alexandra de l'équipe WWOOF France
[oOutlook]<http://www.wwoof.fr/>[cid:image002.png@01D278CA.F879E270]<http://www.facebook.com/pages/Wwoof-France/172038322894280>

Membre de l'association WWOOF International www.wwoofinternational.org<http://www.wwoofinternational.org/>

PAvant d'imprimer cet e-mail, réfléchissons à l'impact sur l'environnement.
ECOSIA <https://www.ecosia.org/> : le moteur de recherche écologique

De : Guillaume Zurbach [mailto:notifications@github.com]
Envoyé : lundi 13 mars 2017 07:40
À : wwoof/webapp <webapp@noreply.github.com>
Cc : Alexandra <alexandra@wwoof.fr>; Author <author@noreply.github.com>
Objet : Re: [wwoof/webapp] Ajouter case à cocher pour photo hôte (#250)


C'est fait ! merci de jeter un coup d'oeil pour confirmer que tout marche bien :)
