### ISSUE TITLE
Ajouter case pour suppression de photo Hôte

### ISSUE THREAD

**Issue by alexxxxxxxxxxxxx** [wwoof/webapp#251]
Ajouter une case afin que l'hôte puisse choisir de supprimer telle ou telle photo

**Comment by gzurbach** [comment]
Ca existe déjà non ?

<img width="298" alt="screen shot 2016-04-21 at 7 27 50 am" src="https://cloud.githubusercontent.com/assets/795927/14712621/c0ee6c3a-0792-11e6-88b2-5510f10085b4.png">

**Comment by alexxxxxxxxxxxxx** [comment]
ce n'est pas bon de boire au bureau !
Excuse-moi.
