### ISSUE TITLE
Renouvellement H : montant "0" affiché

### ISSUE THREAD

**Issue by VeroWWoof** [wwoof/webapp#252]
Hello :) 
Un hôte souhaitant renouveler après avoir le rappel à cotisation a cliqué sur le lien 'renouveler mon adhésion maintenant' contenu dans l'email de rappel et cela le renvoie vers le site avec un montant "0" (voir PJ).  Son email est : Thierry Peel <pitoudeschamps@yahoo.fr>
Merci :)
Bises
V.
![bug hr](https://cloud.githubusercontent.com/assets/12623351/14738269/e8029898-0880-11e6-8509-470929d44c9a.png)

**Comment by VeroWWoof** [comment]
Idem pour francois.heisserer@laposte.net ;)

**Comment by VeroWWoof** [comment]
idem pour Sarah REZZOUG <sarah.rezzoug@orange.fr> 
en attendant, nous allons arrêter d'envoyer les rappels à cotisation ;)

**Comment by gzurbach** [comment]
Fixé !

**Comment by VeroWWoof** [comment]
merci (y)

**Comment by VeroWWoof** [comment]
Pour info, idem pour Jean-Michel Diesnis <jeanmichel.diesnis@gmail.com> (mais le mail de rappel de cotisation lui a été envoyé le 19/04 soit en plein "bug")

**Comment by gzurbach** [comment]
Oui je sais j'ai vu son message, je lui ai déjà répondu. Le bug est bien réglé. Merci de ne pas réouvrir les bugs si ce n'est pas nécessaire :)
