### ISSUE TITLE
Ajouter un picto "refusé" en admin sur la liste de tous les utilisateurs

### ISSUE THREAD

**Issue by alexxxxxxxxxxxxx** [wwoof/webapp#253]
- Nous avons le triangle pour les approuvés ou renou en attente de paiement
- Le sablier pour les en attente d'appro
  Pourrions-nous avoir comme un signe "interdit" pour les refusés ?

Ma demande a une raison ;-)

[cature.docx](https://github.com/wwoof/webapp/files/231575/cature.docx)

**Comment by gzurbach** [comment]
Fait, il y a désormais un panneau "sens interdit" en rouge :)

**Comment by alexxxxxxxxxxxxx** [comment]
C'est top, merci beaucoup.
