### ISSUE TITLE
Durée de vie des mots de passe ?

### ISSUE THREAD

**Issue by VeroWWoof** [wwoof/webapp#254]
Hello, 
Les mots de passe envoyés par le site en cas d'oubli par l'adhérent sont ils temporaires ? 
J'ai le cas d'une W (bernadette.komg <bernadette.komg@orange.fr>) qui utilisait un MDP généré par le site depuis fin août et qui ne fonctionne plus à présent.
Merci :)
Bises

**Comment by gzurbach** [comment]
Non les mots de passe générés n'expirent pas. Je recommande cependant de changer de mot de passe immédiatement une fois authentifié dans le site.

**Comment by VeroWWoof** [comment]
oui c'est ce que je lui ai répondu ! merci (y)
