### ISSUE TITLE
Contacter La Ferme du Bonheur (contact@lafermedubonheur.fr)

### ISSUE THREAD

**Issue by Virg-WF** [wwoof/webapp#257]
Salut Guillaume, Un W m'a contacté pour me dire que le bouton "contacter cet hôte" sur la le profil de La Ferme du Bonheur (contact@lafermedubonheur.fr) ne fonctionne pas. J'ai testé de mon côté et c'est vrai. Il est actif jusqu'au 30 juin et je ne vois ce qui pourrait bloquer...
Bises, Virg.

**Comment by gzurbach** [comment]
Comme discuté ensemble, l'envoi d'emails a été désactivé pour cette ferme dans son profil. Seuls les admins peuvent changer cette option. Donc tout est normal :)
