### ISSUE TITLE
Problème système de messagerie

### ISSUE THREAD

**Issue by Virg-WF** [wwoof/webapp#258]
Re salut ! 
Voici un autre message reçu de la part d'un W :

"Je tiens à vous informer que votre service de messagerie ( contact des
hôtes) est défaillante. En effet, j'ai envoyer un message il y a de cela plusieurs jours à un hôte, en cochant l'option "recevoir ce message" sur ma boîte mail. N'ayant rien reçu moi même, et sans aucun retour de l'hôte au bout de quelques jours, je décide de l'appeler. Il m'a en effet confirmé qu'il n'a jamais reçu mon message. Ce mail donc pour vous avertir sur la non fiabilité de votre système de messagerie."

Bises, Virg.

**Comment by gzurbach** [comment]
Fixé.
