### ISSUE TITLE
Export compta workbench

### ISSUE THREAD

**Issue by Virg-WF** [wwoof/webapp#259]
Salut Guillaume, 
Est-il possible de modifier l'export compta hôte et WWOOFeur en ajoutant les transactions braintree ?
De plus, j'en profite pour te signaler que les WWOOFeurs qui n'ont pas remplis leur adresse postale, ne ressortent pas dans l'export même si leur compte est actif. Peut être as tu une solution pour résoudre ce problème ?
Bises, Virg.

**Comment by gzurbach** [comment]
Fixé !
