### ISSUE TITLE
Question d'un W concernant les messages envoyés d'un iPad

### ISSUE THREAD

**Issue by Virg-WF** [wwoof/webapp#260]
" Nous avons contacté plusieurs hôtes depuis un iPad (connecté au réseau 4G d'un iPhone, avec le partage de connexion) et d'autres depuis un ordinateur (connecté au Wifi). Ceux contacté depuis un ordinateur ont répondu mais pas ceux depuis l'iPad.

Vu qu'il n'y a pas de moyen de vérifier que les messages ont bien été envoyé, pensez vous que le fait de passer par l'iPad (via le réseau de l'iPhone) puisse poser problème avec votre site ? "

Je ne pense pas et normalement, ils devraient avoir reçu une copie du message envoyé sur leur boîte mail (pour la vérification), mais je préfère avoir ton avis sur la question quand même. Bises, Virg.

**Comment by gzurbach** [comment]
Répondu sur Skype.
