### ISSUE TITLE
Ajout filtre/critère pour langues parlées

### ISSUE THREAD

**Issue by VeroWWoof** [wwoof/webapp#261]
Hello l'Amérique, 
Suite à la suggestion d'un WWOOFeur, je crée ce github pour savoir s'il est possible d'ajouter aux critères de recherche d'un hôte : les langues parlées ?
Merci :)
Bises
V

**Comment by gzurbach** [comment]
Il y a déjà un ticket dans GitHub pour ça. Voir #64
