### ISSUE TITLE
Problème affichage carte de France

### ISSUE THREAD

**Issue by Virg-WF** [wwoof/webapp#262]
Salut Guillaume, 
Il y a un petit souci d'affichage de la carte de France ce matin... (en mode connecté ou non). J'ai testé sur chrome et firefox, c'est la même chose.
[bug.docx](https://github.com/wwoof/webapp/files/358963/bug.docx)

Bises, Virg

**Comment by Chinow** [comment]
[Le Blog post relatif à ce changement](http://devblog.mapquest.com/2016/06/15/modernization-of-mapquest-results-in-changes-to-open-tile-access/
)
C'est un changement majeur de l'api de cartographie que nous utilisons.
 

- Il nous faut voir quel protocole de sécurité ils ont utilisé et si celui ci est un standard facilement implementable de notre côté ou si leur plugin leaflet est utilisable dans notre environment Ember.
- Si c'est implementable de notre cote il faut voir si le plan Gratuit nous convient. 15 000 transaction par mois sachant qu'ils ont une description assez precise de 1 transaction, Et j'ai du mal a voir si on dépasserai les quotas gratuits ou non.
- En fonction des résultats de l'investigation, envisager un autre flux de donées pour notre couche de fond.

**Comment by Chinow** [comment]
@gzurbach 
J'ai fait une branche rapide ou j'ai intégré leur librairie leaflet, et ca fontionne. (Il faudrait fixer jsHint parceque j'utilise une globale... mais c'est un quick fix)
 => 15985e7ba928fa66663f624d0cd306281a374a0f

Ce qu'il faudrait faire a partir de ce code est de créer un compte de dev chez MapQuest pour le woof et utiliser cette clé d'API qu lieu de la mienne. (la clé se trouve dans l'URL de téléchargement de l'API dans la balise script)

Et si ca te convient au moins a court terme, merger cette branche et surveiller les quotas.

**Comment by gzurbach** [comment]
Le fix temporaire est en place. Merci Max pour ton aide ! Il faut trouver une solution permanente rapidement.

**Comment by gzurbach** [comment]
Liste des alternatives potentielles :

- https://developer.mapquest.com/plans
- https://developer.here.com/plans/api/consumer-mapping
- https://developers.google.com/maps/pricing-and-plans/#details
- https://www.mapbox.com/pricing/

Liste : http://wiki.openstreetmap.org/wiki/Commercial_OSM_Software_and_Services

**Comment by gzurbach** [comment]
Fixé.
