### ISSUE TITLE
Paiement PayPal avec montant de 0 Euro

### ISSUE THREAD

**Issue by Virg-WF** [wwoof/webapp#263]
je lui ai répondu, qu'on allait voir ça. Bises, Virg.

Ré-bonsoir,

J'ai réussi a réglé le problème en annulant les 2 essais de payement par PayPal et en payant par carte bancaire. Mais je voulais juste vous dire donc que lien PayPal ne marche pas dans la mesure qu'un ordre de paiement est pris en compte mais le choix d'adhésion voulu - donc le montant (€25 dans mon cas), ne l'est pas. Le taux est à €0 - donc la raison pour laquelle je paiement ne passe pas.

Bonne soirée,
Charlotte 

Sent from my iPad
> On 13 Jul 2016, at 18:40, Charlotte Seymour <charlotteseymour5@googlemail.com> wrote:
> 
> Bonsoir Virginie,
> 
> Je vous e-mail car j'ai essayé de vous appeler 3 fois hier durant les heures de permance et je suis tombé à chaque fois sur le message enregistré.
> 
> Je veux m'adhérer en temps que WWOOFEUR (j'étais membre de WWOOF Italia l'année dernière). J'ai créée mon profil mais quand j'ai essayé de payer par PayPal, un ordre de payement à été mis en place, mais rien n'à été débité. J'ai vue cela avec eux et ils m'ont dit que cela venait de votre côté. Pourriez-vous m'aider, s'il vous plaît?
> 
> Je vous remercie d'avance.
> 
> Bien cordialement,
> 
> Charlotte

**Comment by gzurbach** [comment]
Cas rare, on peut ignorer. A réouvrir si ça se reproduit.
