### ISSUE TITLE
Ne pas envoyer de rappel d'adhésion si celle-ci est déjà renouvellée

### ISSUE THREAD

**Issue by VeroWWoof** [wwoof/webapp#264]
Hello, 
Cas de l'hôte https://app.wwoof.fr/host/423/edit  qui apparaissait le 15/07 dans la liste des adhérents à qui nous devions envoyer un rappel car son adhésion "anniversaire" est le 14/08. 
Mais cet hôte avait dès le mois d'avril régler son renouvellement et son adhésion est bien active jusqu'en 08/2017. A mon avis ces cas là ne devraient donc pas recevoir ce "rappel à cotisation" :)
Merci
Bises
V.
ps : j'ai classifié cela en bug mais alors, cela en est un tout petit petit ;)

**Comment by gzurbach** [comment]
Dans le mail de rappel que l'on envoie aux membres on leur dit que s'ils ont déjà renouvelé ils n'ont aucune action à prendre. Mais tu as raison le mieux serait de ne rien envoyer du tout.

**Comment by gzurbach** [comment]
Les rappels sont maintenant envoyés tous les jours automatiquement. Le renouvellement n'étant possible que 30 jours avant expiration et les emails étant eux aussi envoyés 30 jours avant expiration, il est désormais peu probable que ce problème se reproduise.
