### ISSUE TITLE
Bug avec l'envoi de mot de passe ?

### ISSUE THREAD

**Issue by VeroWWoof** [wwoof/webapp#265]
Hello
Depuis 3-4 jours, je reçois pas mal d'emails d'adhérents indiquant qu'ils ont cliqué sur "mot de passe" oublié sans jamais avoir reçu le mot de passe temporaire (en ayant également vérifié dans les spams). Y-a-t-il un pb ?
Merci :)

Ex : 
Sophie Altenkirch <sophie-altenkirch@web.de>
guillaume.daurat@laposte.net
Genevieve Georges <genevievegeorges@gmail.com>

etc.

**Comment by gzurbach** [comment]
Je suis au courant malheureusement. J'ai reçu quelques mails à ce sujet aussi. Dans la plupart des cas c'est parceque nos mails contenant les nouveaux mot de passe sont bloqués par les systèmes de messagerie de destination. Après quelques heures ils sont souvent délivrés. Pour le moment je n'ai pas de meilleure solution mais je vais y réfléchir.

**Comment by gzurbach** [comment]
Le problème était du à un blocage temporaire. Je ferme le bug :)
