### ISSUE TITLE
Open hosts in a new tab

### ISSUE THREAD

**Issue by gzurbach** [wwoof/webapp#266]
Or use pagination ?

**Comment by alexxxxxxxxxxxxx** [comment]
A se réfère ce post ?

**Comment by gzurbach** [comment]
J'ai reçu un message de la part d'un utilisateur :

"Lorsque je consulte la liste des hôtes, si je visite le site d’une annonce d’une énième page, systématiquement quand retourne à la liste je me retrouve au début de celle-ci."

J'ai créé ce bug pour me souvenir de régler ce problème.
