### ISSUE TITLE
Rappels adhésions à terme impossibles à envoyer (chez Véro)

### ISSUE THREAD

**Issue by alexxxxxxxxxxxxx** [wwoof/webapp#268]
voir sa copie d'écran (vero)

![alex](https://cloud.githubusercontent.com/assets/9049131/17961540/aaeef01c-6aac-11e6-967c-d9e15fae7f15.jpg)
![vero](https://cloud.githubusercontent.com/assets/9049131/17961539/aaeeb0fc-6aac-11e6-9fd9-00025d989f05.jpg)

pas de souci chez moi (alex)

Bizarre...
A +

**Comment by gzurbach** [comment]
Véro dit que ça marche en rafraichissant la page :)
