### ISSUE TITLE
Email non reçu

### ISSUE THREAD

**Issue by VeroWWoof** [wwoof/webapp#270]
Hello, 
Une Hôte (paule.schlemaire@gmail.com) dit nous avoir envoyé un message mais aucune de nous ne l'a reçu (ni sur nos boîtes attitrées, ni sur les boîtes hello, feedback...etc). 
Pourrais tu voir s'il y a un bug chez nous derrière cela ?
Merci :)
Bises
V.

**Comment by VeroWWoof** [comment]
annulé : le mail a fini par charger cet aprem sur hello

**Comment by VeroWWoof** [comment]
pour info, ce matin après avoir recherché sur hello, aucune trace ! et cet après-midi oui ! cela peut il être dû à un pb ?

**Comment by gzurbach** [comment]
Cela peut venir de plein de raisons différentes. Si l'email a été envoyé depuis SquareSpace il se peut que le problème vienne d'eux. Sinon ça vient probablement de Office 365. Dans tous les cas ça
