### ISSUE TITLE
cases activités H obligatoirement cochées

### ISSUE THREAD

**Issue by alexxxxxxxxxxxxx** [wwoof/webapp#272]
Voir pj mais j'allais rejeter cet H quand j'ai vu qu'aucune des activités n'avaient été cochées... Bizarre non, car c'est obligatoire ?
Du coup, j'attends le 
[tienscestbizarreca.docx](https://github.com/wwoof/webapp/files/551136/tienscestbizarreca.docx)
go avant de rejeter.

**Comment by gzurbach** [comment]
Je viens de jeter un coup d'oeil dans le code et il semblerait que les activités ne sont pas obligatoires. Je ne sais pas si c'est un oubli par contre. Le problème c'est que l'on a plein d'anciens hôtes qui n'ont pas d'activités car ils sont devenus membres avant que les activités n'existent. Donc ça pourrait poser problème. Faut que je réfléchisse mais en attenant tu peux le rejeter sans soucis.

**Comment by gzurbach** [comment]
Bon je viens de regarder le code. Je pense que ce qui s'est passé c'est que je ne voulais pas rendre le champ obligatoire à l'époque pour une raison qui n'est pas claire. Je viens de rendre ce champ obligatoire, on va voir ce que ça donne :)
