### ISSUE TITLE
Back-end available?

### ISSUE THREAD

**Issue by DarkLotus** [wwoof/webapp#273]
Stumbled across the project and noticed the back-end is mentioned in the initial readme but points to a dead link, is the back-end still open source?

**Comment by gzurbach** [comment]
@DarkLotus thanks for your interest in this project. The back-end used to be open source but we recently made the repo private for security purposes. Happy to provide read access if you are curious.

**Comment by DarkLotus** [comment]
@gzurbach  Hey that would be great, thanks for the speedy reply 👍

**Comment by gzurbach** [comment]
Sent you an email via http://www.gippslandweb.com.au. I'd like to discuss privately before granting you access. Cheers!
