### ISSUE TITLE
Création d'une "bulle" sur le commentaire approuvé d'un W

### ISSUE THREAD

**Issue by VeroWWoof** [wwoof/webapp#277]
Plutôt qu'envoyer un email au W dont le commentaire a été approuvé : faire apparaître une petite bulle sur son commentaire indiquant que celui-ci a été approuvé par l'équipe.

**Comment by gzurbach** [comment]
Nous n'envoyons pas d'emails aux W pour leur indiquer que leur commentaire a été approuvé. Il y a déjà une "bulle" indiquant qu'un commentaire est en attente d'approbation. Donc si la bulle disparait cela indique le commentaire a été approuvé. Alex : est-ce que ça te convient ou tu veux faire quelque chose d'autre ?

**Comment by gzurbach** [comment]
Pardon c'est Véro qui a créé le bug donc la question est pour toi Véro :)

**Comment by alexxxxxxxxxxxxx** [comment]
Pour moi c'est OK comme ça ;-)

**Comment by VeroWWoof** [comment]
ça me va aussi ;)
