### ISSUE TITLE
Format photos en téléchargements pour Hôtes

### ISSUE THREAD

**Issue by alexxxxxxxxxxxxx** [wwoof/webapp#278]
Suite au mail d'un hôte :

Quelques remarques rapides au sujet des photos :
- une photo de présentation de l'hôte, comme elle est proposée pour les WWOOFeurs, pourrait être sympa
- le format de présentation de la structure et celui des photos défilantes n'est pas le même :
-- concrètement, la photo présentant "Les jardins du Piqueberle" n'a aucun sens, car elle coupe Karim
-- je pense qu'il faudrait distinguer les photos de bandeau, défilantes, au format panorama, qui apparaissent quand on est sur la structure de l'hôte, de la photo de présentation, fixe, au format paysage, qui apparaît lorsque l'on parcourt les différents hôtes
-- je pense également que l'on devrait, lorsque l'on insère des photos, les visualiser au format sous lequel elles apparaîtront, ce qui n'est pas le cas aujourd'hui
- 4 photos ci-dessous, la photo communiquée, celle qui apparaît parmi les photos défilantes (correcte), et les deux autres (liste des hôtes et édition de profil) qui sont tronquées"

**Comment by gzurbach** [comment]
Fixé.
