### ISSUE TITLE
Impossible d'approuver un commentaire

### ISSUE THREAD

**Issue by VeroWWoof** [wwoof/webapp#280]
Hello :)
Ce matin, impossible d'approuver les commentaires. 
Sur la page Admin Commentaires, après avoir cliqué sur "approuver", une fenêtre s'ouvre donc (avec le texte du comment, les étoiles...etc). J'ai beau cliqué sur "approuver", la fenêtre ne se ferme pas et le commentaire n'est pas approuvé (vérifié sur la page de l'hôte). Virginie a essayé, idem. Je me suis déconnectée, reconnectée, j'ai actualisé ma page : idem.
Merci !
Bises
V.
PS : j'ai essayé pour
- Laure Panon a commenté La Ferme des Georges
- Kevin Denie a commenté Ferme de Kerdelam

**Comment by gzurbach** [comment]
Fixé ! Alex a confirmé 👍
