### ISSUE TITLE
Mettre à jour 1 page du site après envoi d'un formulaire de contact

### ISSUE THREAD

**Issue by VeroWWoof** [wwoof/webapp#281]
Hello
En faisant des petits tests pour Zendesk aujourd'hui, je me suis rendue compte que lorsqu'on remplit le formulaire de contact puis qu'on clique sur "envoyer", il reste du texte "superflu" (voir PJ). Nous pensons qu'il devrait rester uniquement "merci ! nous vous répondrons au plus vite". 
Merci :)
Véro
![form contact](https://cloud.githubusercontent.com/assets/12623351/20887316/6018f53a-bafa-11e6-846d-60db53f70428.png)

**Comment by gzurbach** [comment]
On a mis en gras c'est le mieux qu'on puisse faire :)
