### ISSUE TITLE
Envois des rappels à cotisation

### ISSUE THREAD

**Issue by Virg-WF** [wwoof/webapp#285]
Salut Guillaume, Lorsque je souhaite envoyer les rappels et que je clique sur "exp ds les 30 proch jours" puis sur  "prénom et nom", le nombre de rappels à envoyer reste à 0. Je dois décocher "prénom et nom" pour voir apparaître le nombre de rappels à envoyer.
[rappels.docx](https://github.com/wwoof/webapp/files/693157/rappels.docx)

**Comment by gzurbach** [comment]
Fixé ! Désolé j'ai fait quelques mises à jour du code et je n'avais pas testé cette page suffisamment.
