### ISSUE TITLE
Modif des frais postaux

### ISSUE THREAD

**Issue by Virg-WF** [wwoof/webapp#286]
Salut Guillaume,

Début d'année oblige, les tarifs de la poste ont changé !
Pour la France : 5.01
Pour l'Europe : 9.91
Pour l'international : 12.15
Guyane.... : 8.91
Polynésie Française... : 13.59

Bises.

**Comment by gzurbach** [comment]
Je me demande si on ne pourrait pas simplifier nos frais d'envois : un prix "France métropolitaine" et un prix "international". Avec tous deux des montants ronds : 5 Euros pour la France et mettons 10 Euros pour l'international (ou 11 ou 12.. peu importe). Je ne comprends particulièrement pas l'intérêt de mettre les DOM-TOM dans leurs propres catégories.

Qu'est-ce que tu en penses ?

**Comment by Virg-WF** [comment]
Salut Guillaume,
On a mis les DOM TOM, ds leur propre catégorie, car le coût du timbre est plus élevé. Pour arrondir les frais postaux, Il faudrait que je voie avec le comptable dans un premier tps (mais pas de suite, car je suis très occupée avec la compta, en cette fin d’année), car ce monsieur est assez pointilleux ! Et je me demande aussi si ça vaut le coup, car de toutes les façons il faudra quand même ajuster ces montants au fur et à mesure afin de ne pas perdre d’argent sur les envois.

Bises, Virg.



De : Guillaume Zurbach [mailto:notifications@github.com]
Envoyé : mardi 17 janvier 2017 02:26
À : wwoof/webapp <webapp@noreply.github.com>
Cc : Virginie Lopez <virginie@wwoof.fr>; Author <author@noreply.github.com>
Objet : Re: [wwoof/webapp] Modif des frais postaux (#286)


Je me demande si on ne pourrait pas simplifier nos frais d'envois : un prix "France métropolitaine" et un prix "international". Avec tous deux des montants ronds : 5 Euros pour la France et mettons 10 Euros pour l'international (ou 11 ou 12.. peu importe). Je ne comprends particulièrement pas l'intérêt de mettre les DOM-TOM dans leurs propres catégories.

Qu'est-ce que tu en penses ?
