### ISSUE TITLE
Commentaire déposé sur un"mystérieux" hôte

### ISSUE THREAD

**Issue by alexxxxxxxxxxxxx** [wwoof/webapp#290]
Le commentaire de Henri Gabolde de dimanche à 21h40 ne mentionne pas de nom d'hôte !
Comment le retrouver ? C'est très bizarre.
Merci.

**Comment by gzurbach** [comment]
Je viens de faire une petite recherche et l'hôte qu'il a commenté n'a simplement pas de nom de ferme ! C'est très rare car le champ est obligatoire depuis bien longtemps mais cet hôte n'a pas mis à jour sa description depuis... plus de deux ans :)

https://app.wwoof.fr/host/435/edit

PS : je recommande de donner un nom à cette ferme. Soit appeler l'hôte et en discuter avec lui, soit mettre un truc générique comme "Ferme biologique certifiée AB et Nature & Progrès".

**Comment by alexxxxxxxxxxxxx** [comment]
Super merci beaucoup, je viens de lui donner un nom.
Mais comment l’as-tu retrouvée toi ?

Alexandra de l'équipe WWOOF France
[oOutlook]<http://www.wwoof.fr/>[cid:image002.png@01D278CA.F879E270]<http://www.facebook.com/pages/Wwoof-France/172038322894280>

Membre de l'association WWOOF International www.wwoofinternational.org<http://www.wwoofinternational.org/>

PAvant d'imprimer cet e-mail, réfléchissons à l'impact sur l'environnement.
ECOSIA <https://www.ecosia.org/> : le moteur de recherche écologique

De : Guillaume Zurbach [mailto:notifications@github.com]
Envoyé : lundi 6 février 2017 18:25
À : wwoof/webapp <webapp@noreply.github.com>
Cc : Alexandra <alexandra@wwoof.fr>; Author <author@noreply.github.com>
Objet : Re: [wwoof/webapp] Commentaire déposé sur un"mystérieux" hôte (#290)


Je viens de faire une petite recherche et l'hôte qu'il a commenté n'a simplement pas de nom de ferme ! C'est très rare car le champ est obligatoire depuis bien longtemps mais cet hôte n'a pas mis à jour sa description depuis... plus de deux ans :)

https://app.wwoof.fr/host/435/edit

PS : je recommande de donner un nom à cette ferme. Soit appeler l'hôte et en discuter avec lui, soit mettre un truc générique comme "Ferme biologique certifiée AB et Nature & Progrès".

**Comment by gzurbach** [comment]
Je suis allé voir directement dans Workbench. Comme un vrai Samurai !

**Comment by alexxxxxxxxxxxxx** [comment]
aligatô !

Alexandra de l'équipe WWOOF France
[oOutlook]<http://www.wwoof.fr/>[cid:image002.png@01D278CA.F879E270]<http://www.facebook.com/pages/Wwoof-France/172038322894280>

Membre de l'association WWOOF International www.wwoofinternational.org<http://www.wwoofinternational.org/>

PAvant d'imprimer cet e-mail, réfléchissons à l'impact sur l'environnement.
ECOSIA <https://www.ecosia.org/> : le moteur de recherche écologique

De : Guillaume Zurbach [mailto:notifications@github.com]
Envoyé : lundi 6 février 2017 21:04
À : wwoof/webapp <webapp@noreply.github.com>
Cc : Alexandra <alexandra@wwoof.fr>; Author <author@noreply.github.com>
Objet : Re: [wwoof/webapp] Commentaire déposé sur un"mystérieux" hôte (#290)


Je suis allé voir directement dans Workbench. Comme un vrai Samurai !
