### ISSUE TITLE
2 WWOOFeurs pour une adhésion SOLO

### ISSUE THREAD

**Issue by VeroWWoof** [wwoof/webapp#291]
Hello, voir le W : https://app.wwoof.fr/wwoofer/95543/edit 
il a une adhésion WO1 soit pour 1 WWOOFeur et pourtant il a pu renseigner le nom d'un second W (qui apparaît bien sur son profil).
Merci :)

**Comment by Virg-WF** [comment]
Le choix d'ajouter ou non un second W, se fait avant le paiement, lors de l'inscription sur le site. Cette personne a donc rentré (sciemment ou non) le nom du second W et à choisi ensuite de prendre une adhésion solo.

**Comment by VeroWWoof** [comment]
Oui je le sais, mais cela ne devrait pas être possible, non ?

**Comment by VeroWWoof** [comment]
Faisant suite à la demande du WWOOFeur, j'enlève le second W mais voici la copie d'écran
![wo](https://cloud.githubusercontent.com/assets/12623351/22776604/8fc31ae2-eeb0-11e6-893b-2af32a571b0f.png)

**Comment by VeroWWoof** [comment]
Du coup, ne devrait-on pas faire une extraction des adhésions WO1 et WOB1 où la case "oui je fais du W avec qq'un" est cochée ?

**Comment by VeroWWoof** [comment]
Idem avec le cas de  jeankb@aol.com qui a pris une adhésion WO1 et qui pourtant a pu ajouter son époux en second WWOOFeur.
![2eme w](https://cloud.githubusercontent.com/assets/12623351/23256954/df83152a-f9c1-11e6-8cd0-aedaa33a41c5.png)

**Comment by gzurbach** [comment]
C'est un peu compliqué à résoudre comme problème mais on pourrait en discuter lors de notre prochaine réunion.

**Comment by gzurbach** [comment]
Ce bug est désormais fixé. Les informations sur le second W sont maintenant saisies directement sur la page de paiement de l'adhésion donc plus moyen de gruger :)

**Comment by VeroWWoof** [comment]
C'est super ! merci beaucoup :D petite question subsidiaire : comment faire à présent pour nous, en tant qu'admin, pour modifier cette info ou mettre un second W (pour ceux ayant souscrit une adhésion duo avant ce changement) ?
Merci !

**Comment by gzurbach** [comment]
Je t'expliquerai tout ça jeudi lors de la réunion. Rappelle-moi d'en parler :)

**Comment by Virg-WF** [comment]
le second WWOOFeur n’apparaît plus sur le profil ? J'ai voulu faire l'ajout d'un W2 en passant par Worbench, mais il ne s'affiche pas sur le profil. J'ai reçu aussi des emails de W qui me disent avoir bien inscrit un W2, mais celui-ci n’apparaît sur leur profil.

**Comment by VeroWWoof** [comment]
Je confirme. J'ai été recontactée par dida730@hotmail.fr (profil auquel j'avais ajouté un second W). Elle m'indique auj que ce 2nd nom a disparu (c'est vrai). 
Merci !

**Comment by gzurbach** [comment]
C'est bon c'est fixé ! Le second W apparaît de nouveau sur le profil. J'ai migré environ 14.000 second W de l'ancienne​ table vers la nouvelle.

**Comment by Virg-WF** [comment]
Super !
