### ISSUE TITLE
Création du profil hôte impossible

### ISSUE THREAD

**Issue by Virg-WF** [wwoof/webapp#294]
Salut Guillaume,
Je pense qu'il y a un souci car les hôtes ne peuvent pas enregistrer et soumettre leur candidature à Alex (Cf. PJ)
[github.docx](https://github.com/wwoof/webapp/files/790667/github.docx)

**Comment by gzurbach** [comment]
Oups, fixé !

**Comment by Virg-WF** [comment]
Merci !
Bises,

Virginie de l'équipe WWOOF France
[oOutlook]<http://www.wwoof.fr/>[cid:image002.png@01D278CA.F879E270]<http://www.facebook.com/pages/Wwoof-France/172038322894280>

Membre de l'association WWOOF International www.wwoofinternational.org<http://www.wwoofinternational.org/>

PAvant d'imprimer cet e-mail, réfléchissons à l'impact sur l'environnement.
ECOSIA <https://www.ecosia.org/> : le moteur de recherche écologique

De : Guillaume Zurbach [mailto:notifications@github.com]
Envoyé : mardi 21 février 2017 17:09
À : wwoof/webapp <webapp@noreply.github.com>
Cc : Virginie Lopez <virginie@wwoof.fr>; Author <author@noreply.github.com>
Objet : Re: [wwoof/webapp] Création du profil hôte impossible (#294)


Oups, fixé !
