### ISSUE TITLE
Impossibilité de créer un profil W

### ISSUE THREAD

**Issue by VeroWWoof** [wwoof/webapp#295]
Hello, 
Ci-dessous des emails de (futurs) WWOOFeurs qui ont créé un compte WWOOF mais qui n'ont pu créér leur profil WWOOFeur. 
- julia24111@live.fr 
- j.carole@hotmail.com 
Virginie m'indique que tu as corrigé un bug identique pour les Hôtes, ça a sans doute corrigé celui ci aussi mais dans le doute :)
Merci

**Comment by gzurbach** [comment]
Véro le bug qui affectait les H ne devrait pas affecter les W. Je viens de regarder sur le site et nous avons des dizaines de nouveaux W aujourd'hui donc je ne pense pas que le site ait un soucis. Quel était le problème de ces W exactement ? Ont-il réessayé depuis ?

**Comment by VeroWWoof** [comment]
Ces retours nous ont été faits en début de semaine et j'en ai pris connaissance via Zendesk jeudi matin seulement... sans doute qu'entre temps cela s'était résolu. Et tant mieux !
Le pb était : en cliquant sur "créer un profil W", il n'y avait pas de bouton "enregistrer" (ou confirmer/valider...).

**Comment by gzurbach** [comment]
OK on va considérer que c'est bon alors 👍
