### ISSUE TITLE
hôte qui a fait un renouv W sans avoir de profil W 

### ISSUE THREAD

**Issue by Virg-WF** [wwoof/webapp#296]
#Salut Guillaume,
Un hôte a payé sa cotis afin de renouv son adh et nous a contacté parce qu'il n'était pas visible sur le site. 
J'ai donc regardé de plus près au niveau des paiements reçus et il s'avère qu'il a payé pour une adh WWOOFeur SOLO (25 euros) alors que celui-ci n'a pas de profil WWOOFeur. C'est donc normal qu'il ne se voit pas sur la carte... J'ai regardé son profil et il se trouve qu'il a bénéficier l'année dernière d'une adh W gratuite, du coup ça explique qu'il est reçu un appel à cotis W, mais je me pose la question : Est ce possible qu'il y ait eu un bug lors de l'import de la base ou tu penses plutôt que c'est une erreur humaine ?

**Comment by gzurbach** [comment]
Je pense que c'est une erreur humaine car l'import de la base date de 2014 et son adhésion gratuite date de 2016. Il faut juste changer le type de l'adhésion dans Workbench (replacer W par H, et WO1 par HR).
Aussi petit rappel, si tu as besoin d'envoyer des informations confidentielles ne les mets pas dans GitHub, tout est public ici ! Tu peux m'envoyer ce genre de "bugs" par email c'est mieux.
