### ISSUE TITLE
Adhésion WO1 à 30.01 euros !

### ISSUE THREAD

**Issue by VeroWWoof** [wwoof/webapp#298]
Salut
Nous avons été contactés par un W (email : angrsksn@gmail.com )
qui nous dit ceci "j' ai voulu m'inscrire sur une WWOOFeur 25 euros, mais je me suis trompée de choisir(j'ai choisi deux personne 30 euros). puis-je changer ?"
J'ai pensé au début qu'il avait pris une adhésion DUO au lieu d'une SOLO mais non, le code de l'adh est bien WO1 avec un montant de 30.01 euros. Comme si les frais postaux (pour envoi en France) s'étaient ajoutés à son adh de 25 euros. 
Virginie a vérifié dans Braintree, c'est le seul. 
A priori, ça doit être un petit bug !
Merci 

**EDIT : Virginie et moi avons essayé de reproduire le bug en vain.**

**Comment by gzurbach** [comment]
Je viens de faire de gros changements sur la page de nouvelle adhésion et je pense avoir fixé le bug. A réouvrir si ça se reproduit :)
