### ISSUE TITLE
Impossible d'enregistrer les coordonnées GPS d'un H

### ISSUE THREAD

**Issue by VeroWWoof** [wwoof/webapp#299]
Salut, 
Voir l'H https://app.wwoof.fr/host/4330/address : impossible de sauvegarder véritablement ses coordonnées GPS qui sont : 
Latitude : -21.183051 
Longitude : 55.825052
Je clique sur 'enregistrer' mais l'hôte apparaît toujours en pleine mer sur la carte et effectivement quand je retourne sur la page coordonnées, les champs liés aux coordonnées GPS sont vides !
Merci

**Comment by gzurbach** [comment]
Fixé ! Je ne sais pas ce que j'ai fait mais ça a marché pour moi :)
