### ISSUE TITLE
Mauvais renvoi de lien site EN partie LOGIN-connectée

### ISSUE THREAD

**Issue by alexxxxxxxxxxxxx** [wwoof/webapp#301]
Les liens cassés en public ont été corrigés mais celui-ci n'est pas sur squarespace public...

https://app.wwoof.fr/users/new 
I accept the terms and rules of WWOOF .. . = lien HS à renvoyer vers charte en anglais

Merci.

**Comment by gzurbach** [comment]
Le bug a déjà été reporté par Véro (voir #288). Je ferme celui-ci car c'est un doublon.
