### ISSUE TITLE
Bug sur profil W

### ISSUE THREAD

**Issue by VeroWWoof** [wwoof/webapp#302]
https://app.wwoof.fr/wwoofer/103791

Hello, 

Quand sur ce profil, on clique sur 'envoyer un message', cela renvoie à la création d'un profil Hôte. 
Merci !

V.

**Comment by gzurbach** [comment]
C'est "normal" dans le sens où on assume qu'un utilisateur qui veut contacter un W est probablement un H. Par conséquent si un utilisateur clique sur le bouton pour contacter un W mais qu'il n'a pas encore de profil H, alors on le redirige vers la page de création de profil H. Ceci va changer avec la nouvelle messagerie car désormais tous les utilisateurs pourront échanger entre eux, W vers H, H vers W mais aussi H vers H et W vers W.

**Comment by VeroWWoof** [comment]
Merci ! on peut clôturer ce (faux) bug 💃
