### ISSUE TITLE
Impossible de supprimer un commentaire

### ISSUE THREAD

**Issue by VeroWWoof** [wwoof/webapp#306]
![comment](https://user-images.githubusercontent.com/12623351/26976857-04fad38a-4d26-11e7-869b-ca05986826b4.png)

Je souhaitais supprimer le commentaire de cet hôte mais pas de bouton "supprimer" 
Merci !

**Comment by gzurbach** [comment]
Tu veux supprimer le commentaire du wwoofeur ou la réponse de l'hôte ?

Je ne crois pas avoir mis en place de système pour supprimer les réponses
aux commentaires mais ce serait facile à ajouter si besoin. Sinon tu peux
simplement l'enlever dans workbench mais c'est moins pratique.

**Comment by VeroWWoof** [comment]
Je souhaitais supprimer la réponse de l'hôte qui n'a pas grand chose à voir :)
Merci !

**Comment by gzurbach** [comment]
Fixé!
