### ISSUE TITLE
SQL views

### ISSUE THREAD

**Issue by davidwwoof** [wwoof/webapp#307]
Salut
je pense qu en touchant a la structure de la base de données les scripts en ont pris un coup. 
Tu peux me tenir au jus stp?

merci

David

**Comment by gzurbach** [comment]
Quel vues en particulier ?

**Comment by davidwwoof** [comment]
vero export hotes (et wwoofeurs je suppose mais j ai pas poussé plus loin)

**Comment by gzurbach** [comment]
`SELECT * FROM wwoof.vero_export_hotes;` works for me. 

Could you send me the exact SQL command you are running and the error message you're seeing?
