### ISSUE TITLE
Lien déclaration cassé dans confirmation H

### ISSUE THREAD

**Issue by alexxxxxxxxxxxxx** [wwoof/webapp#313]
Le lien ne fonctionne plus d'après le message d'un H ce matin, merci.
Je te les mets en pj car je les ai revu il y a peu (ces nouvelles versions ont déjà été mises sur le site par David), peut-être que cela a un rapport.

[declarationsWWOOFEN.pdf](https://github.com/wwoof/webapp/files/1124001/declarationsWWOOFEN.pdf)
[declarationsWWOOFFR.pdf](https://github.com/wwoof/webapp/files/1124002/declarationsWWOOFFR.pdf)

**Comment by gzurbach** [comment]
Le lien de la declaration ou ? Dans le mail de bienvenue aux hôtes ?

**Comment by alexxxxxxxxxxxxx** [comment]
Mmmm... le mail 
"Bonjour Alexandra,

Dans le mail de réponse à mon adhésion du 6/08/16, il y a (entre autres) un lien vers la déclaration du wwoofeur, mais il ne fonctionne plus.


car sur le site on a vérifié et tout est bon.

**Comment by gzurbach** [comment]
Fixé.
