### ISSUE TITLE
MESSAGERIE : supprimer ou archiver des messages ?

### ISSUE THREAD

**Issue by VeroWWoof** [wwoof/webapp#315]
Remarque d'un hôte : pouvoir supprimer ou archiver certains messages pour "s'y retrouver" et faire un peu de tri :)

Merci !

**Comment by gzurbach** [comment]
Fixé. Les utilisateurs peuvent désormais archiver leurs conversations. 

Je n'ai pas l'intention à ce state de permettre la suppression car les messages de seraient supprimés que pour un des deux utilisateurs, ce qui n'a aucun sens.
