### ISSUE TITLE
Répondre directement par email dans Messagerie interne

### ISSUE THREAD

**Issue by davidwwoof** [wwoof/webapp#316]
Permettre aux adhérents de répondre directement via leur email aux demandes de messagerie WWOOF.
Lorsque la réponse part directement de la boite email perso de l'adhérent, il faut que cet échange soit enregistrer dans l'historique de la messagerie interne.

**Comment by gzurbach** [comment]
Fixé.

**Comment by davidwwoof** [comment]
yes!!!!! merci :)


Le 10 mars 2018 12:05 AM, Guillaume Zurbach <notifications@github.com> a écrit :

Fixé.
