### ISSUE TITLE
Lien cassé "rules" lors de l'inscription

### ISSUE THREAD

**Issue by davidwwoof** [wwoof/webapp#320]
Mettre à jour le lien de "rules" vers la charte.
![3](https://user-images.githubusercontent.com/9443308/29835611-d5107622-8cf2-11e7-96cd-fbbe86c51463.jpeg)

**Comment by davidwwoof** [comment]
Il faut changer le lien https://www.wwoof.fr/wwoofing-charter/
par
https://www.wwoof.fr/charte-wwoofing

**Comment by gzurbach** [comment]
Fixé !
