### ISSUE TITLE
Adhésion en tant qu'hôte: options "Ne pas afficher mon num de tel" et "désactiver l'envoi d'emails"

### ISSUE THREAD

**Issue by davidwwoof** [wwoof/webapp#322]
Lorsqu'on s'inscrit en tant qu'hôte, on peut cocher les deux options "Ne pas afficher mon num de tel" et "désactiver l'envoi d'emails".
Comment peut-on contacter les hôtes alors?
Je pense que tu devrais laisser un choix unique entre ces deux boutons, non?
![1](https://user-images.githubusercontent.com/9443308/29860821-96be275a-8d67-11e7-9428-8fb6a495b2d1.jpeg)

**Comment by gzurbach** [comment]
David seuls les admins peuvent cocher la case pour désactiver l'envoi d'emails. C'est un choix que l'on a fait lorsque l'on a mis en place la nouvelle messagerie.
