### ISSUE TITLE
Toutes inscirptions impossibles sur le site !

### ISSUE THREAD

**Issue by alexxxxxxxxxxxxx** [wwoof/webapp#332]
J'ai fait un test ce matin est effectivement j'ai eu ce message "certaines informations sont manquantes ou invalides", alors que tout est bon.
![image](https://user-images.githubusercontent.com/9049131/30960575-b62a6494-a443-11e7-8ef5-d8826ae38ba8.png)
[capture.docx](https://github.com/wwoof/webapp/files/1340375/capture.docx)

**Comment by gzurbach** [comment]
Je viens de faire un test et ça fonctionne bien pour moi. Nous avons des dizaines de nouveaux membres tous les jours dons je ne pense pas qu'il y ait un problème majeur. Cela dir je vois bien que tu as réussi à provoquer ce bug donc si tu arrives à reproduire de manière constante je pourrais investiguer plus en détails lors d'un Skype.

**Comment by alexxxxxxxxxxxxx** [comment]
d'accord, merci pour ton écoute !

**Comment by gzurbach** [comment]
Fixé !
