### ISSUE TITLE
Trouver les infos concernant le W2

### ISSUE THREAD

**Issue by Virg-WF** [wwoof/webapp#337]
Mis à part le prénom et l'âge que je retrouve dans la présentation, je ne trouve pas le nom du W2, ce qui est gênant lorsque je dois envoyer un livret papier pour 2 personnes.

**Comment by gzurbach** [comment]
Lorsque tu édites une adhésion tu as accès aux infos du second W. C'est pas super pratique mais est-ce que ça suffit en attendant ?

**Comment by Virg-WF** [comment]
Peut-être que je regarde au mauvais endroit, puisque la mise en page à changé, mais je ne trouve pas le nom de famille des seconds W (seule information manquante, sur le site, pour l'envoi des lp duo). Je vais donc les récupérer sur workbench, pour le moment.

**Comment by gzurbach** [comment]
Lorsque tu édites une adhésion tu peux voir les infos du second W.
Par exemple : https://app.wwoof.fr/membership/103905/edit

**Comment by gzurbach** [comment]
Fixé. Le nom de famille des W s'affiche désormais sur leur profil.
