### ISSUE TITLE
Récupérer les items codes WOB1 et WOB2 

### ISSUE THREAD

**Issue by Virg-WF** [wwoof/webapp#338]
Suite aux modifications de la page d’adhésion, il n’y a plus de distinction visuelle entre une simple adhésion en ligne ou une adhésion avec un livret papier en supplément sur le site et braintree. C’est donc désormais soit WO1 ou WO2. Je ne peux donc plus me fier à ces item code qui me faisaient gagner du temps et dois donc désormais filtrer par prix, ce qui pourrait être, lors de gros mois, source d’erreur. 
Guillaume, y’aurait- il un moyen de récupérer ces item code WOB1 et WOB2 ?

Virginie.

**Comment by gzurbach** [comment]
Je ne peux pas remettre WOB1 et WOB2. Par contre je viens de mettre un nouveau champ dans Braintree à côté du code item :

<img width="622" alt="screen shot 2017-12-09 at 6 57 13 pm" src="https://user-images.githubusercontent.com/795927/33801531-cdb75f42-dd12-11e7-8afe-6bba878cf9fb.png">

Ça ne concerne que les nouvelles adhésions à partir d'aujourd'hui. Désolé pour les ennuis que j'ai causés !

**Comment by Virg-WF** [comment]
Peux-tu faire de même dans l'export compta hôte et WWOOFeur, stp

**Comment by gzurbach** [comment]
Je viens de modifier la view `vir_compta_wwoofeurs` pour ajouter une colonne `includeBooklet` qui contient 0 ou 1 (0 = non, 1 = oui).
L'autre view (vir_compta_hotes) n'a pas besoin de changer puisque les hôtes ne peuvent pas commander de livret.

**Comment by Virg-WF** [comment]
Super, merci Guillaume et j’en profite pour te souhaiter une très bonne année à toi et aussi à Laura. Bises.

Virginie de l'équipe WWOOF France P/O Sophie Marie, Présidente

[oOutlook]<http://www.wwoof.fr/>[cid:image002.png@01D278CA.F879E270]<http://www.facebook.com/pages/Wwoof-France/172038322894280>

Membre de l'association WWOOF International www.wwoofinternational.org<http://www.wwoofinternational.org/>

PAvant d'imprimer cet e-mail, réfléchissons à l'impact sur l'environnement.
ECOSIA <https://www.ecosia.org/> : le moteur de recherche écologique


De : Guillaume Zurbach [mailto:notifications@github.com]
Envoyé : lundi 1 janvier 2018 04:21
À : wwoof/webapp <webapp@noreply.github.com>
Cc : Virginie <virginie@wwoof.fr>; Author <author@noreply.github.com>
Objet : Re: [wwoof/webapp] Récupérer les items codes WOB1 et WOB2 (#338)


Je viens de modifier la view vir_compta_wwoofeurs pour ajouter une colonne includeBooklet qui contient 0 ou 1 (0 = non, 1 = oui).
L'autre view (vir_compta_hotes) n'a pas besoin de changer puisque les hôtes ne peuvent pas commander de livret.
