### ISSUE TITLE
Afficher un peu plus d'infos sur les W

### ISSUE THREAD

**Issue by alexxxxxxxxxxxxx** [wwoof/webapp#344]
Remettre en infos dispo le nom et âge des W (comme avant)

**Comment by alexxxxxxxxxxxxx** [comment]
Parfait, merci !

**Comment by davidwwoof** [comment]
on peut voir les infos du WWOOFeur quand on est connecté en tant qu'admin mais pas en tant que membre normal

**Comment by gzurbach** [comment]
À quelle page fais tu référence David ?

**Comment by gzurbach** [comment]
Ok je comprends maintenant je m'en occupe bientôt.

**Comment by gzurbach** [comment]
Fixé !
