### ISSUE TITLE
Limiter la capacité de wwoofeurs à deux par hôte

### ISSUE THREAD

**Issue by alexxxxxxxxxxxxx** [wwoof/webapp#345]
juste garder 1 W et 2 W

**Comment by gzurbach** [comment]
Que fait-on des hôtes qui on déjà saisi 3 et 4+ wwoofeurs ?

**Comment by alexxxxxxxxxxxxx** [comment]
Est-il ossible de les basculer sur 2 ?

**Comment by gzurbach** [comment]
C'est fait, voir mon email pour plus de détails.
