### ISSUE TITLE
Un utilisateur suspendu a toujours accès au site s'il ne s'est pas délogué

### ISSUE THREAD

**Issue by alexxxxxxxxxxxxx** [wwoof/webapp#351]
C’est le cas de https://app.wwoof.fr/users?isSuspended=true&searchTerm=ducharne qui a continué d'envoyer des messages depuis sa suspension.
Nous avons compris en testant. Si tu te délogues tu ne peux plus te connecter mais si tu restes connecté tu as toujours accès ! Et c’est très embêtant. 
Merci de ce que vous pourrez faire rapidement.

**Comment by gzurbach** [comment]
Oups, c'est bon c'est réglé ! Ça marchait avant mais j'ai fait des changements récemment dans le système de validation des utilisateurs et j'ai oublié de remettre ça en place.

**Comment by alexxxxxxxxxxxxx** [comment]
Merci c’est super d'avoir fait si vite ! ! ! ! :-)
