### ISSUE TITLE
Mise à jour liste activités hôtes à cocher

### ISSUE THREAD

**Issue by alexxxxxxxxxxxxx** [wwoof/webapp#61]
Pourrais-tu mettre les activités ci-dessous pour que les hôtes les cochent (en séparant bien la première liste de la seconde). Merci.

Légumes
Fruits
Petits fruits
Animaux
Aquaculture
Pisciculture
Apiculture
Transformation : fromages, huiles essentielles, confitures…
Foresterie
Céréales
Cueillette sauvage
Vignoble
Boulangerie
Brasserie

Permaculture
Biodynamie
Agroécologie

**Comment by alexxxxxxxxxxxxx** [comment]
Les activités 


Potager > Vegetable plot
Maraîchage > Market gardening
 Verger > Orchard	 	
Céréales > Cereals
 Elevage > Livestock
 Apiculture > Bee-keeping
 Vignoble > Vineyards
 Bois >  Forestry
 Cueillette sauvage > Foraging 
 Transformation : pain, fromages, huiles essentielles, confitures… > Baking, Preserves ie Jams and Chutneys, Essential oils, Cheese making...
Boulangerie > Bakery
 Brasserie	> Brewery





 Et un peu en exergue

Permaculture > Permaculture
 Biodynamie > Biodynamic agriculture
 Agroécologie > Agroecology

**Comment by alexxxxxxxxxxxxx** [comment]
Pour l'écoconstruction, on hésite car si on le met il faudrait qu'un message s'affiche lorsque l'hôte ne cochera que cette case du genre :
Le WWOOFing concerne avant tout les activités agricoles, l'écoconstruction - seule - ne peut suffire.

**Comment by alexxxxxxxxxxxxx** [comment]
coucou crois-tu qu'on puisse voir ça bientôt ou pas ?

Aïe aïe pas sur les doigts... Je sais que tu as des choses plus importantes...

**Comment by gzurbach** [comment]
Non y'a pas de soucis haha. C'est juste que c'est un peu plus compliqué que prévu :

 - L'activité " Transformation : pain, fromages, huiles essentielles, confitures…" est trop longue donc je dois mettre un mot simple et une petite bulle de description quand on passe la souris dessus.
 - Mettre certaines activités "en exergue" n'est pas simple pour des raisons techniques.

Il faut juste que je me penche dessus pendant une aprem.

**Comment by gzurbach** [comment]
Je viens d'ajouter "Brasserie" aujourd'hui.

Pour le reste il faudra qu'on discute lors de notre Skype vendredi.

**Comment by alexxxxxxxxxxxxx** [comment]
OK on en discutera alors, merci pour l'ajout de BRASSERIE.
C’est une top idée la bulle de survol ;-)

**Comment by gzurbach** [comment]
J'ai ajouté cueillette sauvage et différencié potager et maraîchage. Tous les hôtes qui avaient coché 'légumes' ont maintenant 'potager' **et** 'maraîchage'. Il faudra dire dans le mail qu'on envoie aux hôtes cette semaine de cocher/décocher en fonction de ce qu'ils font vraiment.

**Comment by alexxxxxxxxxxxxx** [comment]
Ok, merci !
