### ISSUE TITLE
Permettre l'édition des adhésions

### ISSUE THREAD

**Issue by Virg-WF** [wwoof/webapp#84]
Est il possible d'ajouter un code pour ceux qui auraient choisi une adh en ligne uniquement et qui  finalement souhaiteraient recevoir le livret papier en plus ?

**Comment by gzurbach** [comment]
Pour le moment la solution consiste à éditer l'adhésion du membre directement via Workbench. Le code peut être changé (de WO1 vers WOB1 par exemple) ainsi que le total.

**Comment by gzurbach** [comment]
C'est fait ! J'enverrai un email séparément pour expliquer comment ça marche :)
