### ISSUE TITLE
Profil hôte : Téléphone rentré au début disparaît ensuite...

### ISSUE THREAD

**Issue by alexxxxxxxxxxxxx** [wwoof/webapp#89]
Tout est dit

**Comment by gzurbach** [comment]
Je viens de tomber sur ce bug par accident dans le code... j'arrive pas à croire que je ne l'ai pas vu plus tôt, c’était devant mes yeux !

**Comment by alexxxxxxxxxxxxx** [comment]
c'est surtout lorsque c'est devant nos yeux justement... MERCI !
