### ISSUE TITLE
achat adh en ligne +livret papier

### ISSUE THREAD

**Issue by Virg-WF** [wwoof/webapp#90]
Je ne vois rien dans la base en dure, ni sur le détail des adhésions concernant les frais postaux. De plus, lorsque je procède moi même à l'activation des comptes, pour les paiements par chèque, les centimes n'apparaissent pas dans le détail des adhésions de l'adhérent.

**Comment by gzurbach** [comment]
Le problème des centimes a été réglé je crois (merci de confirmer).
Pour ce qui est des frais postaux ils sont inclus dans la colonne 'total' de la table 'memberships'.
Le site fait la somme de l’adhésion et des frais postaux.

**Comment by Virg-WF** [comment]
Pour les ctmes je me suis aperçue qu'il ne fallait, en fait, pas utiliser de virgule mais un point donc maintenant que je sais c'est ok. Pour les frais postaux, c'est ok aussi. Je pensais juste que je pourrais les trouver ailleurs...
