### ISSUE TITLE
Photos hôtes se chargent mais...

### ISSUE THREAD

**Issue by alexxxxxxxxxxxxx** [wwoof/webapp#92]
Lorsqu'un hôte ajoute une photo, il peut cliquer sur ENREGISTRER juste à droite, mais ça ne fonctionne pas. Par contre, ça fonctionne si on clique sur ENREGISTRER (sous activités proposées aux WWOOFeurs).

Lorsqu'un hôte ajoute une photo il y a une légende à mettre si on veut, mais où apparait-elle après ? Mais de toute façon, pour le moment même si tu en mets elle n'est pa spris en compte...

**Comment by gzurbach** [comment]
Fixé.

**Comment by alexxxxxxxxxxxxx** [comment]
J'ai vu oui, c'est trop beau, la classe <3
