### ISSUE TITLE
view hosts contacts after viewing wwoofer contacts

### ISSUE THREAD

**Issue by davidwwoof** [wwoof/webapp#93]
Salut Guillaume,

J’ai remarqué un problème, voici les manifs pour reproduire le problème:

Je me log en tant que wwoofeur actif (david@wwoof.fr)
je fais une recherche sur les wwoofeurs ( tranier francois)
je regarde le profil de Francois tranier ainsi que ses adhésions
je fais une recherche sur les hotes, je sélectionne l’hôte qui m intéresse (n’importe quel hôte)
la fiche hôte qui s’affiche spécifie que les informations de contact sont réservés aux membres actifs (alors que mon adhésion est valide)

Je suis obligé de sélectionner “mes adhésions” pour pouvoir ensuite avoir accès aux informations complètes des hôtes

Bone journée

David

**Comment by gzurbach** [comment]
Fixé.
