### ISSUE TITLE
Alerte changement annonce hôte

### ISSUE THREAD

**Issue by alexxxxxxxxxxxxx** [wwoof/webapp#98]
Si tu peux faire en sorte que toutes les semaines on ait une alerte pour tels et tels hôtes qui ont changé leurs TEXTES ce serait bien. Je ne sais pas encore si tu peux mettre ça en admin... ou faire un envoi par mail... On en a parlé à la maison.

**Comment by gzurbach** [comment]
Doublon de #68.
