### ISSUE TITLE
Extraction données pour livret papier

### ISSUE THREAD

**Issue by alexxxxxxxxxxxxx** [wwoof/webapp#99]
ça va devenir URGENT.
Je voulais te mettre une pj pour que tu vois comme il est fait... demande-la moi quand tu seras dessus merci.
ps : il faudrait que les fichiers soient chez l'imprimeur mi janvier au plus tard... si possible évidemment !
De mon côté je me renseigne pour ce que tu m'as dit

**Comment by gzurbach** [comment]
On est bons là-dessus non ?

**Comment by alexxxxxxxxxxxxx** [comment]
Pour cette édition oui, je vais faire de mon mieux ;-)

Je crois que tu as des choses plus importantes/urgentes mais c’est clair qu’on devra revenir dessus.




Alexandra de l'équipe WWOOF France
logoOutlook
 <http://www.wwoof.fr/> www.wwoof.fr

 <http://www.facebook.com/pages/Wwoof-France/172038322894280> http://www.facebook.com/pages/Wwoof-France/172038322894280
Membre de l'association WWOOF International  <http://www.wwoofinternational.org/> www.wwoofinternational.org

P Avant d'imprimer cet e-mail, réfléchissons à l'impact sur l'environnement. 
ECOSIA : le moteur de recherche écologique

 

De : Guillaume Zurbach [mailto:notifications@github.com] 
Envoyé : lundi 19 janvier 2015 01:41
À : wwoof/webapp
Cc : Alexandra Denais
Objet : Re: [webapp] Extraction données pour livret papier (#99)

 

On est bons là-dessus non ?

**Comment by alexxxxxxxxxxxxx** [comment]
Si on peut revoir des choses (plus tard) ce serait pas mal car, par exemple, il y a bcp de <br> que j'ai dû enlever du livret. J'ai fait un gros nettoyage mais pour l'édition papier seuement et c'est dommage.
Pourrais tu m'écrire des requêtes si je te liste les "imperfections" ? Et je ferai ce nettoyage moi-même.

**Comment by gzurbach** [comment]
Oui bien sur.

**Comment by gzurbach** [comment]
Sachant que tous les <br> ont été retirés et que les &#8217; on été remplacés, est-ce que je peux fermer ce bug ?

**Comment by alexxxxxxxxxxxxx** [comment]
je vais checker car on trouve aussi des <br>. je te fais uen liste de tous les caractère sspéciaux très bientôt.

**Comment by alexxxxxxxxxxxxx** [comment]
je vais checker car on trouve aussi des >br>
Je te fais une liste de tous les caractères spéciaux très bientôt.

**Comment by gzurbach** [comment]
Je pense avoir tout nettoyé. Si tu trouves encore des erreurs dis-le moi.
